### ISSUE TITLE
Consider EnvironmentScreen

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#1001]
`EnvironmentScreen` would be a mechanism to allow workflows to pass ViewEnvironment values out to the rendering system.

From this discussion: https://github.com/square/workflow/pull/999#discussion_r387871586

**Comment by zach-klippenstein** [comment]
I still disagree with this pattern (workflow setting environment values) because it's unnecessary because we already have a way to do this: the rendering. Workflows communicate to the view layer by emitting renderings. That's the pipeline. This just adds another way to do the same thing, which will inevitably result in confusion about "should this value go in the rendering or the environment."

`ViewEnvironment` is specifically for "views" to talk to other "views" about "view" concerns outside of the renderings created by the workflow. The decision about which to use is clear: if a container needs to communicate a view concern to its children, use `ViewEnvironment`. If a workflow needs to communicate to its children, use props. However if a workflow needs to communicate view concerns to its _view's children_, that's a sign the workflow knows too much about the view layer.

**Comment by bencochran** [comment]
For me, this addresses the “workflow needs to communicate view concerns to its view's _children_” case. And I disagree that this necessarily means the workflow knows too much about the view layer.

The theme example for me illustrates the example well. I have a view-side notion of “theme” providing colors, insets, etc. Somewhere in my app I have a setting to change the theme (or maybe even have it change automatically for time of day). I have this ThemingWorkflow (or whatever) hold a theme in its state and wrap a child workflow, maybe even rendering out a modal theme picker when appropriate. That ThemingWorkflow _could_ have a render like:

```swift
extension ThemingWorkflow {
    func render(state: State, context: RenderContext<ThemingWorkflow>) -> Rendering {
        return contentWorkflow
            .mapRendering { content in
                ThemedScreen(
                    theme: state.theme,
                    content: content
                )
            }
            .rendered(with: context)
    }
}

struct ThemedScreen: Screen {
    var theme: Theme
    var content: AnyScreen

    func viewControllerDescription(environment: ViewEnvironment) -> ViewControllerDescription {
        let themedEnvironment = environment.setting(\.theme, theme)
        return content.viewControllerDescription(environment: themedEnvironment)
    }
}
```

Which hoists the theme up into the view-side environment<sup>[1](#theming-footnote-1)</sup>. Which is the exact same role that `EnvironmentScreen` provides as a generic wrapper, where instead we would have this:

```swift
extension ThemingWorkflow {
    func render(state: State, context: RenderContext<ThemingWorkflow>) -> Rendering {
        return contentWorkflow
            .mapRendering { content in
                content.environment(\.theme, theme)
            }
            .rendered(with: context)
    }
}
```

I guess my question is, is the first approach (`ThemedScreen`) alright in your mind and it’s just the `EnvironmentScreen` that seems like a smell? Or would you propose a different flow of information for this sort of workflow?

---

<a name="theming-footnote-1">1</a>: I could even have them more separate and provide a `ThemedViewController` that gets described in `viewControllerDescription`, contains a `DescribedViewController` that holds the `content` rendering and modifies the environment on the way through, but that’s just adding a view controller layer for no real gain in my opinion.

**Comment by rjrjr** [comment]
The `ThemedScreen` approach is exactly what I would have suggested, and to me demonstrates that `EnvironmentScreen` isn't necessary. I think `EnvironmentScreen` unnecessarily blurs the bright line we've been able to maintain between workflow and view concerns.

I understand how `EventScreen` works and even with that I find the second snippet kind of magical and confusing.

**Comment by rjrjr** [comment]
And thinking about this more, even `ThemingWorkflow` seems like more of an intrusion into workflow-land than is ideal. In Android I'd do this entirely on the view side, presuming that the source of truth for theming already lives there — still pass the info down via `ViewEnvironment`, but do so in the code that connects the workflow runtime's rendering stream to the root view controller. I'm already doing something similar to pass device-specific info like screen size and orientation into the `ViewEnvironment`, something like:

```kotlin
    val hints = ContainerHints(viewRegistry) +
        (ScreenSizeHint to device.currentScreenSize)

    contentView = WorkflowLayout(workflowScope!!.createContext(activity))
        .also { workflowLayout ->
          workflowLayout.start(
              renderings = runner.renderings,
              hints = hints
          )
          activity.setContentView(workflowLayout)
        }
```

But maybe involving workflow makes more sense on iOS? I don't really know the theming / night mode mechanics there.

**Comment by zach-klippenstein** [comment]
Agree with Ray that `ThemeWorkflow` seems odd. If anything, it should be a stateless workflow that just wraps its child in a marker rendering, which defines all the theme data on the view side. If the workflow needs to be in charge of some aspects of the theme (e.g. "day mode/night mode"), that should be a flag the workflow can set on the rendering, but the workflow shouldn't be defining the details of the theme itself.

**Comment by bencochran** [comment]
If I’m reading it right, that approach feels to me like it encourages people to put state into their view layer, which seems antithetical to the role of Workflow. I’m not necessarily saying that we’d want a Workflow to be specifying the entirety of a theme (colors, fonts, etc), but I also think generally the boundary between “non-view” and “view” concerns is often fuzzier than it is clear.

This proposal doesn’t change any flow of responsibility, it just admits that fuzziness and reduces boilerplate when needing to push workflow state into view environment.

This can be added entirely outside of the module, so I’m not going to fight hard for this. But it _is_ likely to be an extension I end up making in my own projects that use Workflow.

**Comment by dhavalshreyas** [comment]
I think we're all in agreement that the `ViewEnvironment` gets augmented through the `Screen / Rendering`. 

The proposal here was simply to add a convenience extension to either the `Screen` or `Workflow` to augment the `ViewEnvironment` by setting values. 

In general, I think this will be a useful convenience. However, as @bencochran mentions, it's easy for anybody to add this convenience on their end. The only concern here might be that each module will have it's own version of this extension.

**Comment by dhavalshreyas** [comment]
Since this does not affect the core libraries and is easy enough to extend, I'd like to drop this from the `v1` milestone.

**Comment by rjrjr** [comment]
+1. Okay to close it, or do you want to keep it around for later discussion?

**Comment by bencochran** [comment]
Makes sense to drop 1.0. This would be net-new and can be added later if we settle on something.

**Comment by rjrjr** [comment]
Tracked separately for Swift, and already implemented in Kotlin.
