### ISSUE TITLE
Android: Make sure that multiple back stack containers don't break view persistence

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#1007]
E.g., body is a back stack, in a few frames, covered by a panel that is in a few frames. Does the view state all get restored?

I suspect the answer will be no because of the hard coded id in `BackStackContainer`.

**Comment by zach-klippenstein** [comment]
@rjrjr This doesn't require an API change, does it? If not, I want to remove it from the 1.0.0 milestone.

**Comment by rjrjr** [comment]
Dup of various more detailed issues.
