### ISSUE TITLE
Kotlin: Profile unit test execution time

### ISSUE THREAD

**Issue by bnvinay92** [square/workflow#1016]
It seems like the first test run from each test class takes much longer than the rest. Not sure if that's cause of junit or Workflow.
<img width="381" alt="Screen Shot 2020-03-10 at 4 51 07 AM" src="https://user-images.githubusercontent.com/22435681/76269411-f5f98200-628a-11ea-9e87-061b49af661a.png">

**Comment by zach-klippenstein** [comment]
This is a junit thing, not workflow.
