### ISSUE TITLE
Convert Container Screens in Sample to Generic Containers [swift]

### ISSUE THREAD

**Issue by dhavalshreyas** [square/workflow#1046]
Instead of using `AnyScreen` content, use a generic `ScreenType`.

* `CrossFadeScreen`
*  `BackStackScreen` (#1167)

**Comment by JustinDSN** [comment]
Just to leave a verbal conversation comment trail, we talked about how this also inspires a SwiftUI like IfScreen<TrueScreen, FalseScreen> that could be used to swap out a given screen should a condition evaluates to true.

 Relates to #1164

**Comment by dhavalshreyas** [comment]
`CrossFadeScreen` is meant to handle transitions between different screens. We're not planning on switching that from `AnyScreen` at this time.
