### ISSUE TITLE
Add tests to the TicTacToe sample project

### ISSUE THREAD

**Issue by kingreza** [square/workflow#1117]
Many use the TicTacToe example as a point of reference. We should ensure it has enough coverage to demonstrate various testing techniques.

**Comment by asthatrivedi** [comment]
I'm actually working on adding AlertScreen in TicTacToe. I can start adding some tests to the app.

**Comment by kingreza** [comment]
I'm actually halfway through doing it myself. Wouldn't it mind running with you in a bit and see if there is room for more.
