### ISSUE TITLE
WorkflowViewStub should propagate its visibility to its child

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#1119]
It is a somewhat common use case (it's come up twice in the last couple weeks) to try to modify the visibility of a `WorkflowViewStub`, in order to show/hide its views. This kind of works correctly if the actual child view has already been created (i.e. after the first `update` call). However, it doesn't work if you set the visibility before `update` and I don't think it will work if you change the rendering type which requires replacing the child view after setting the visibility.

We can solve this by explicitly making sure we copy `visibility` to the child when new views are created.

One question this raises is what about syncing other properties? Well, so far visibility is the only one that has come up. It seems to be a common enough use case that I think it's worth solving it, but I don't think we need to solve the general problem at this point.

**Comment by rjrjr** [comment]
https://github.com/square/workflow-kotlin/pull/28
