### ISSUE TITLE
Finalize github strategy

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#1129]
We have discussed (where?) various ways we might reorganize our code before releasing it. We should go one more round and make sure this is all resolved. Related topics (some of which we maybe already settled, sorry to rehash if so) include:

 * Separate repos for Swift, Kotlin and docs? 
    * Appeal of decoupling
    * Are separate version numbers a win or a lose?
    * Adds complexity to keeping shared resources like docs in sync.
    * Remember that Cocoa Pods and Package Manager rely on github, harder to change our minds later

 * Kotlin has bootstrap templates that are shockingly out of date. What's a better strategy for maintain them? Should we delete them?

 * #1120 calls for moving the Compose sample to a separate repo

 * Gather whatever repos we come up with under organization https://github.com/squareworkflow

**Comment by digitalbuddha** [comment]
I vote to split repos as I haven't had any reason to go into swift code. It just makes search harder for me :-)

**Comment by AquaGeek** [comment]
> Separate repos for Swift, Kotlin, and docs

I'm _very_ much in support of that direction. The docs repo can serve as the "homepage" for the project and point folks to all the other pieces.

> Are separate version numbers a win or a lose?

I think they are a major win. We don't implement features in lockstep anyway, and right now we have several releases that don't contain any changes on one of the platforms. In a post-1.0 world, if we have to implement a breaking change on only one platform it seems strange that the major version of the other platform would also get bumped up.

> I vote to split repos as I haven't had any reason to go into swift code. It just makes search harder for me :-)

Same. I struggle a lot with being overwhelmed by all the issues, PRs, commits, releases, etc that are for the other platform.

**Comment by rjrjr** [comment]
I'm really reluctant to split. It was _hard_ for us to get a consistent API, and we're still working on it.  I worry that losing a shared issue tracker and losing lock step releases is going make drift even harder to fight.

I also suspect that splitting the repos is also going to be a lot more work than we think, especially as we find a new home for the shared docs. And — shared docs! Do they move to a third repo?

**Comment by zach-klippenstein** [comment]
In previous discussions, I believe there was agreement that docs should stay in the original/"main" repo, and language specific libraries should be split off.

I don't think splitting would _necessarily_ make it harder to stay consistent, although we might need to adjust our processes. But it's still easy to link issues across repositories, and I believe we could create an organization-level project that can be used from all 3 repos.

I think the noise issue is a big one — I haven't minded glancing at changes that are happening on the Swift side, even though I don't review PRs, but I know we (kotlin) have been a lot noisier. 

Versioning seems like the biggest issue, but splitting isn't the only solution there. We could also, eg, start using language-specific version tags (eg `kotlin-v1.0.5`). This might make the Releases page a bit messier, and might look odd to consumers using SPM which directly references tag names.

**Comment by zach-klippenstein** [comment]
Discussed offline, decided to pull out into `workflow-swift` and `workflow-kotlin` repositories under the Square org. I've filed #1186 and #1187 to track extracting swift and kotlin libraries, respectively.

**Comment by AquaGeek** [comment]
@zach-klippenstein Should we close this issue, then?

**Comment by zach-klippenstein** [comment]
I was thinking of this as a parent of the two, so we could close it once all the code is out of this repo. But my LOGF is extremely low.
