### ISSUE TITLE
WorkflowViewStub + Constraint/RelativeLayout Bug

### ISSUE THREAD

**Issue by wardellbagby** [square/workflow#1138]
If you have a `WorkflowViewStub` inside of a `ConstraintLayout` (or a `RelativeLayout`) and try to constrain against it, your constraint will fail.

Here's an example of what I mean:
https://github.com/wardellbagby/workflow-view-stub-layout-bug/blob/3afc6ea33284b78272397d97e213a3df0dfd6d42/app/src/main/res/layout/hello_goodbye_layout.xml

In the linked example, you would expect that the `hello_message` would be below `stub`, but they actually end up on top of each other.

You can easily reproduce this in this repo here:
https://github.com/wardellbagby/workflow-view-stub-layout-bug

**Comment by rjrjr** [comment]
Related: https://stackoverflow.com/questions/47164398/how-to-use-viewstub-in-constraintlayout#comment107877715_47668638

**Comment by rjrjr** [comment]
https://github.com/square/workflow-kotlin/pull/28
