### ISSUE TITLE
Cannot access class 'com.squareup.workflow.diagnostic.WorkflowDiagnosticListener'

### ISSUE THREAD

**Issue by wardellbagby** [square/workflow#1139]
When starting a new project and including `implementation 'com.squareup.workflow:workflow-ui-core-android:0.26.0'` in your `build.gradle` file, when attempting to do something like:

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentWorkflow(viewRegistry) {
      WorkflowRunner.Config(HelloWorkflow, Unit)
    }
  }
```

you won't be able to build your app.

What's happening is that `WorkflowRunner.Config` has an optional parameter: 
`diagnosticListener: WorkflowDiagnosticListener? = null`. 

`WorkflowDiagnosticListener` lives in `'com.squareup.workflow:workflow-tracing:0.26.0'`, which isn't being provided as apart of the API of `'com.squareup.workflow:workflow-ui-core-android:0.26.0'`

**Comment by zach-klippenstein** [comment]
`WorkflowDiagnosticListener` lives in the `workflow-runtime` module (https://github.com/square/workflow/blob/485af5a000393140b80695e56f819f76972b0848/kotlin/workflow-runtime/src/main/java/com/squareup/workflow/diagnostic/WorkflowDiagnosticListener.kt), so something weird must be going on here. Can you post the full error?

**Comment by wardellbagby** [comment]
Of course.

Full error, when building `./gradlew :app:installDebug`

```
> Task :app:compileDebugKotlin FAILED
e: /Users/wardell/Development/workflow-view-stub-constraint-layout/app/src/main/java/com/example/helloworkflow/WorkflowActivity.kt: (15, 22): Cannot access class 'com.squareup.workflow.diagnostic.WorkflowDiagnosticListener'. Check your module classpath for missing or conflicting dependencies
```

I also have a repro repo here: https://github.com/wardellbagby/workflow-view-stub-layout-bug

Just need to comment out the `implementation com.squareup.workflow:workflow-tracing:0.26.0'` in `app/build.gradle`

**Comment by zach-klippenstein** [comment]
Oh, you don't need the tracing artifact, you just need the runtime artifact, which is specified as an `implementation` dependency in `workflow-ui-core-android` instead of `api`.
