### ISSUE TITLE
WorkflowViewStub lacks parity with ViewStub

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#1141]
In particular, it offers no way to set the id of swizzled in views. While fixing that, it'd probably be least surprising if its API matched that of ViewStub as much as possible -- offer an inflatedId attribute, proxy calls to setVisible, etc.

**Comment by 0legg** [comment]
Should resolve #1138

**Comment by zach-klippenstein** [comment]
Since `ViewStub` seems to have some issues itself, I think we should close this issue in favor of #1138. @rjrjr WDYT?

**Comment by rjrjr** [comment]
Probably, but let's keep them open and I'll work on them in parallel.

Related use case that came up today: when copying the id from the stub to the inflated view, don't clobber the latter's id if it's already been set. Should probably emulate this:

```
     * Returns the id taken by the inflated view. If the inflated id is
     * {@link View#NO_ID}, the inflated view keeps its original id.
```

**Comment by rjrjr** [comment]
@zach-klippenstein WRT:

> Since `ViewStub` seems to have some issues itself

Are there specific things you're looking at?

**Comment by rjrjr** [comment]
https://github.com/square/workflow-kotlin/pull/28
