### ISSUE TITLE
Github Actions isn't working with the gradle cache anymore

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#1152]
Github seems to have stopped recursively expanding environment variables, so our `GRADLE_BUILD_CACHE` variable that is set to `$HOME/.gradle/caches` gets resolved literally as `$HOME/.gradle/caches`, which is obviously not the real path.

Furthermore, `${{ env.HOME }}` resolves to the empty string, so I'm not sure how to get the home directory anymore.

Some exploration of what broke was done in #1131.

**Comment by Kiskae** [comment]
You might want to consider turning the problem around and defining a custom `GRADLE_USER_HOME` instead of using the default `$HOME/.gradle`, then caching `$GRADLE_USER_HOME/caches`. If the caching mechanism is path-relative it might even be possible to isolate it to the current build instead of using the user environment.

**Comment by zach-klippenstein** [comment]
I agree that would be ideal, but I couldn't figure out how to specify a custom cache path when running Gradle. I only saw `--project-cache-dir` which I tried, but it didn't seem to affect all the caches. There's also `--gradle-user-home` which I missed the first time. I'll try again, one of those should definitely work.

**Comment by Kiskae** [comment]
`--project-cache-dir` seems to control where the local build artifacts (that dont end up in `/build`) go (`<projectDir>/.gradle`), while `--gradle-user-home` controls the global wrapper/module cache location. (`<HOME>/.gradle`)

**Comment by zach-klippenstein** [comment]
https://github.com/square/workflow-kotlin-compose/pull/30
