### ISSUE TITLE
Replace FinishWith with ExitState interface.

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#117]
what if states could implement an interface like this:

```kotlin
interface ExitState<R> {
  val result: R
}
```

And entering such a state is the only way to finish. Reaction is no longer a public type, onReact() always returns S. It's truly a state transition. 

State machine authors get more control over how you leave, with multiple exits if they need it. Really good cleanup hook too.

**Comment by rjrjr** [comment]
I don't think that an `ExitState` would ever be emitted by the state stream.

**Comment by steveinflow** [comment]
>`onReact` always returns S
Sounds like a good simplification. And no need to figure out a name for `Reaction`/`StateTransition`. 

>State machine authors get more control over how you leave, with multiple exits if they need it.
I'm not sure what this means? Can't we already make `O` a sealed class?

**Comment by rjrjr** [comment]
I ran into this because I wanted to do some cleanup work that varied based on the result type. I've created my own `Stopping` state, and had to come up with an assertion to enforce that we don't call `FinishWith` from any other state.

**Comment by zach-klippenstein** [comment]
It breaks the typing a little. Anyone who's doing a `when` on the state type would need to explicitly ignore the exit states (including, notably, `onReact` itself).

Also, it might be less clear from just reading through an `onReact` body which cases will finish the workflow. But maybe the way most reactors are written in the real world, this information is buried enough that this wouldn't really be any less readable. Could be remedied by a naming convention too, although I prefer naming conventions that the compiler can enforce.

**Comment by rjrjr** [comment]
WRT the when() bit, I think most of that code will be in the same module: the
`Renderer`, or serializer code, so it's reasonable for them to be in on the
secret. This is already happening a bit anyway as we create `Starting` states.

In more complex situations we could do something like this:

```kotlin
sealed class ReactorState

object Starting : ReactorState()
data class Exit(val result: Result) : ExitState<Result>, ReactorState()

sealed class VisibleState : ReactorState() {
  object ScreenOne: VisibleState()
  object ScreenTwo: VisibleState()
}
```

```kotlin
class MyLauncher(
  val reactor : MyReactor<ReactorState, …>
) : Launcher<VisibleState, …> {
  fun launch(
    initialState: VisibleState, 
    workflows: WorkflowPool
  ) : Workflow<VisibleState, …> {
    return reactor.launch(initialState, workflows)
      .switchMapState { 
        if (it is VisibleState) just(it) else never()
      }
  }
```

WRT the readability, I think it's easy enough to give the exit states obvious
names. And are we really losing compiler enforcement? If I want to stop, I
still have to implement `ExitState<R>`, it's not like I can accidentally fail
to provide a result value.

**Comment by rjrjr** [comment]
That's a good point about `onReact()` having to ignore the exit states. :(

**Comment by rjrjr** [comment]
Withdrawn. Every single (non-Rx) `onReact()` method would be impacted, especially non-Rx ones that want to use `when()` properly. 

I bet we've had this conversation before.
