### ISSUE TITLE
Reactor.kt documentation should start by describing what the Reactor interface is for and how to use it

### ISSUE THREAD

**Issue by kirillzh** [square/workflow#122]
The documentation for `Reactor.kt` starts with describing how `Workflow`s work: `A factory for [Workflow]s implemented as state machines that...`, and it's very useful documentation but when I read it the very first time it threw me off, I think it would be less confusing if the documentation started with description of what the `Rector` interface is, what is it useful for and how to use it.

**Comment by kirillzh** [comment]
Actually not sure if this is still relevant considering #111.

**Comment by zach-klippenstein** [comment]
We are going to document everything thoroughly before hitting 1.0.
