### ISSUE TITLE
Cleanup ReactorWorkflow result implementation once we're on kotlin 1.3

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#15]
There's a bug in pre-1.3 when using the `broadcast` coroutine builder with the `Unconfined` dispatcher and `CONFLATED` capacity.

The `broadcast` helper starts the coroutine lazily (because items send before the first subscriber are lost). When the consumer subscribes, there’s a race between starting the broadcast coroutine and the channel actually realizing it has a subscriber it should be sending values to. The start wins, and because both are using the unconfined dispatcher, the broadcast coroutine seems to finish before the subscription actually happens so the consumer only sees an empty, closed channel.

Pre-1.3, line 16 never gets hit. The same code works fine in 1.3.
```kotlin
fun main(args: Array<String>) {
    val producer = GlobalScope
        .broadcast(Unconfined, capacity = CONFLATED) {
            println("producer sending")
            send("hi")
            println("producer sent")
        }
        .apply { invokeOnClose { println("producer closed") } }

    GlobalScope.launch(Unconfined) {
        println("consumer started")
        val consumer = producer.openSubscription()
        println("consumer subscribed")
        consumer.consumeEach {
            // This line never gets hit on pre-1.3.
            println("consumer received: $it")
        }
        println("consumer finished")
    }
}
```

We can work around this for now, but that should be cleaned up once we're on 1.3.

**Comment by rjrjr** [comment]
Blocked by #35

**Comment by zach-klippenstein** [comment]
Reactors have been deprecated, this is obsolete.
