### ISSUE TITLE
Should WorkflowContext extension methods not try to be clever with inlines?

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#194]
I’m thinking of getting rid of the `idempotenceKey: Any`/`key: String` distinction in `WorkflowContext` and just forcing you to always pass a string key. It sucks and I hate it but the current strategy of generating a fancy idempotence key for you means you can’t call those methods from generic workflows that don’t know their types.

cc @rjrjr @timdonnelly

**Comment by rjrjr** [comment]
I just don't have enough experience w/v2 yet to make the call. Are you sure that having to provide the strings won't be a bigger burden than, say, losing the generic workflows?

Although that's kind of a devil's advocate question, really. The nice thing about the explicit idempotence key is that it's right in your face, reduces the amount of mystery around "is this thing going to keep running or what?"

I assume we _always_ always have to provide it, not just when we need to disambiguate?

**Comment by rjrjr** [comment]
The string would also probably be super helpful with debugging messages.

**Comment by rjrjr** [comment]
What's the comparable code in Swift look like?

**Comment by zach-klippenstein** [comment]
```swift
func subscribe<Action>(signal: Signal<Action, NoError>)
```
It doesn't even accept an _optional_ string key, and I couldn't quickly find the impl but I'm guessing it just uses the `Action` type, since Swift doesn't erase generics. @timdonnelly can you confirm?

**Comment by zach-klippenstein** [comment]
I think I have a reasonable solution. Instead of allowing `Any` for the idempotence key, make the "raw" functions take a `KType` along with a `String`. This is much harder to misuse, and is maybe even more clear about what the parameters are for. Then I'm more comfortable exposing those functions publicly, without using separate names.
