### ISSUE TITLE
WorkflowUI shard is flaky

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#201]
See
 - https://travis-ci.com/square/workflow/jobs/186541541
 - https://travis-ci.com/square/workflow/jobs/186875344

> The command "set -o pipefail && xcodebuild -workspace SampleApp.xcworkspace -scheme WorkflowUI-Unit-Tests -destination platform\=iOS\ Simulator,OS\=10.1,name\=iPad\ Pro\ \(9.7-inch\) build test | xcpretty" exited with 134.

**Comment by timdonnelly** [comment]
Neat: https://github.com/Microsoft/azure-pipelines-tasks/issues/8840

**Comment by zach-klippenstein** [comment]
I think it's actually flat out broken, not just flaky. Can we just turn it off for now?

**Comment by JustinDSN** [comment]
I think this issue is resolved now.
