### ISSUE TITLE
makeSink describes what the function does, but is not super scannable

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#203]
`makeSink` describes what the function does, but it doesn't necessarily make the function more readable given how it's used:
```kotlin
return MyScreen(
  onClick = context.makeSink { emitOutput(Foo) },
  onBack = context.makeUnitSink { emitOutput(Bar) }
)
```
 
When you're reading the code, you don't care that the context is "making a sink", you only care that you're trying to specify an event handler. It might be better if the name described the intention of the caller, instead of the way the method fulfills that intention:
```kotlin
return MyScreen(
  onClick = context.handle { emitOutput(Foo) },
  onBack = context.handleUnit { emitOutput(Bar) }
)
```

cc @qrazhan

**Comment by zach-klippenstein** [comment]
Pinging @timdonnelly @rjrjr and @davidapgar for discussion.

**Comment by zach-klippenstein** [comment]
Another thing we could do, at least in Kotlin, is make `WorkflowContext` the receiver of the `compose` method, so then you could do stuff like:
```kotlin
return MyScreen(
  onClick = doAction { emitOutput(Foo) },
  onBack = doUnitAction { emitOutput(Bar) }
)
```

**Comment by davidapgar** [comment]
In the context of what we're doing in swift, the `makeSink` is returning a type that is an actual `Sink` generic around the `Action` type, so the name makes sense.

For the terse variant of this (where we're not explicitly using an `Action` type), we could explore name changes, but the base case has this be accurate, as you're returned a `Sink` that you will use later on in the compose method.

**Comment by rjrjr** [comment]
WRT _make WorkflowContext the receiver of the compose method_, not sure I'm following you. What would this turn into?

```
  override fun compose(
    input: PlayerInfo,
    state: Turn,
    context: WorkflowContext<Turn, CompletedGame>
  ): GamePlayScreen {
    return GamePlayScreen(
        playerInfo = input,
        gameState = state,
        onTakeSquare = context.makeSink { event -> state.onTakeSquare(event) },
        onQuit = context.makeUnitSink { emitOutput(CompletedGame(Quitted, state)) }
    )
  }
```

**Comment by rjrjr** [comment]
Would things scan any better if we simply tweak `makeSink` to `makeEventSink`?

```
    return GamePlayScreen(
        playerInfo = input,
        gameState = state,
        onTakeSquare = context.makeEventSink { event -> state.onTakeSquare(event) },
        onQuit = context.makeUnitSink { emitOutput(CompletedGame(Quitted, state)) }
    )
```

**Comment by rjrjr** [comment]
Re: 

>In the context of what we're doing in swift, the makeSink is returning a type that is an actual Sink generic around the Action type, so the name makes sense.

> For the terse variant of this (where we're not explicitly using an Action type), we could explore name changes, but the base case has this be accurate, as you're returned a Sink that you will use later on in the compose method.

My understanding is that Kotlin doesn't have the `Sink` type because it isn't useful w/o associated types. Given that, isn't it basically the case that Kotlin has only _terse variant_ methods? If so, seems like there is no reason for the `sink` term to show up in Kotlin at all.

So…we can focus on making sure the terse variants are consistent? Perhaps:

```
    return GamePlayScreen(
        playerInfo = input,
        gameState = state,
        onTakeSquare = context.onEvent { event -> state.onTakeSquare(event) },
        onQuit = context.onAction { emitOutput(CompletedGame(Quitted, state)) }
    )
```

**Comment by zach-klippenstein** [comment]
We don't have a sink type because it would just be `(T)->Unit` so instead of adding a layer of naming/abstraction we're just using the function type directly.

@qrazhan WDYT about `onEvent`?

**Comment by qrazhan** [comment]
`onEvent` sgtm! A big improvement over `makeSink`.

**Comment by zach-klippenstein** [comment]
@timdonnelly @davidapgar WDYT?

**Comment by davidapgar** [comment]
As long as you're good with it varying as `makeSink` in Swift, when we're making a sink. 

Having the other be `onEvent` sounds good to me when it's just a closure to immediately handle the event and update seems like a good name.
