### ISSUE TITLE
Drop reflection workarounds in favor of real reflection.

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#211]
The version of Buck that we're using internally strips service loader configurations from metadata. This issue is known and was supposedly fixed: facebook/buck#1897. Until we have upgraded our internal builds and verified that things actually work, however, we can't use most reflection features in this library and have some hacky workarounds. Those should be removed once we can use real reflection.

If you're a Square, see the [internal Slack discussion.](https://square.slack.com/archives/C1MDTM2FR/p1553296594178200).

**Comment by ZacSweers** [comment]
Fwiw, confirmed the fix does indeed work since we're updated. @jbarr21 and I put it through it's courses with our various annotation processors and SPI-based plugins for internal tools

**Comment by zach-klippenstein** [comment]
Awesome! We've started bumping our internal version but need to iron out some merge conflicts with our buck fork.
