### ISSUE TITLE
Too hard / impossible to provide intitial state from empty snapshot.

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#220]
If you save `Snapshot.EMPTY`, it may be impossible to provide the correct initial state because you can't see the initial input from `restoreState`. I'm inclined to fix this by making the return value from `restoreState` nullable, and calling `initialState` when null is returned from there.

With that done, we can provide default implementations for both methods and make snapshotting opt-in, which I increasingly believe is the right thing to do.

cc @zachklipp 

```
fun snapshotState(state: StateT): Snapshot = Snaphot.EMPTY

fun restoreState(snapshot: Snapshot) : StateT? = null
```

**Comment by zach-klippenstein** [comment]
I would rather make `restoreState` take the `InputT` and then the default (or custom) implementation can call `initialState` itself.

**Comment by zach-klippenstein** [comment]
Is this blocking you?

**Comment by rjrjr** [comment]
No, just noticed it.

**Comment by rjrjr** [comment]
And that approach SGTM

**Comment by zach-klippenstein** [comment]
I'm also hesitant to give them default implementations, because I _want_ to force people to think about snapshotting when they write a stateful workflow.

**Comment by rjrjr** [comment]
Yeah…

Yeah, agree, default implementations could quickly create a big hole that
we'd have to dig ourselves out of.
