### ISSUE TITLE
Inline Coordinators

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#234]
AC

 * The functionality that we're leaning on Coordinators for is instead built into ViewRegistry

There isn't _that_ much there, and we can probably benefit by tweaking it to allow multiple coordinators per view.

**Comment by rjrjr** [comment]
Generous points estimate b/c we'll need to iterate on the api

**Comment by zach-klippenstein** [comment]
cc @Helios175

**Comment by zach-klippenstein** [comment]
This is done.
