### ISSUE TITLE
Add stateless workflow convenience extensions to Swift

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#236]
In Kotlin, we recently (#219, #213) refactored our `Workflow` type to be a general type, with two subtypes: `StatefulWorkflow` (was `Workflow`) and `StatelessWorkflow` (something we had before, but now more obviously a directly first-class citizen and sibling of `StatefulWorkflow`). So far the feedback from Android devs has been positive.

This is not a huge change, mostly just naming, so should we adopt it in Swift as well?

cc @davidapgar @timdonnelly @bencochran

**Comment by rjrjr** [comment]
Alternative for Swift:

When a Workflow’s state is Void, it’s typically meaningless to have a makeInitialState or workflowDidChange that’s different than the following:

```swift
extension Workflow where State == Void {
    func makeInitialState() -> State {
        return ()
    }
    func workflowDidChange(from previousWorkflow: Self, state: inout State) {
    }
}
```

We should consider providing a default extension on Workflow when State == Void that implements those as such. If a workflow needs to, say, perform a side effect in either of those, they can still implement them and not use the default implementation.

**Comment by rjrjr** [comment]
Seems reasonable to diverge here, since Swift is nicer than Kotlin can be.
