### ISSUE TITLE
Add an input-update channel to WorkflowHost

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#247]
AC: It is possible to send updated inputs to a WorkflowHost.

While it's possible to work around the lack of this method, doing so is cumbersome.

**Comment by zach-klippenstein** [comment]
We shouldn't have to work around anything, we own the API 🙂

The only reason it doesn't have this yet is because we didn't need it when I wrote it.

**Comment by rjrjr** [comment]
This is definitely needed, we're already hacking around the lack of it in production.
