### ISSUE TITLE
Stale lambdas on repeated WorkflowContext.compose() calls?

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#261]
Debugging with @mbrubin56-square, and I think we've found a problem with repeated calls to WorkflowContext.compose() on a child, maybe related to it emitting multiple output and receiving multiple input.

The flow is something like:

 * when(state) is ParentStateA, we start the child with a lambda that captures ParentStateA'
 * The child emits output, so that lambda fires and takes us to ParentStateB
 * when(state) is ParentStateB, a compose call keeps the child running and does other work
 * That work is done we enterState(ParentStateA''), with new information
 * when(state) is ParentStateA, the original compose call is made, with a new lambda capturing ParentState''
 * The child emits more output, the lambda fires, but it's the lambda from the start of this recipe, that capture ParentStateA'. 
 * We crash because the expected new information is null.

He's working around this by giving the parent workflow a `latestState` field that gets updated from the ParentStateA case, and having the lambda capture that instead. Which is gross.

**Comment by rjrjr** [comment]
Maybe clues: 

 * ParentStateA and ParentStateB give the child different input
 * ParentStateB composes it in with a `noop()` action in the lambda

Something like:

```
    return when (state) {
      is ParentStateA -> {
        context.compose(
            childWorkflow,
            input = Foo
        ) {
          when (it) {
            is ChildAllDone -> enterState(OtherParentState(state.valueAddFromStateB)
            is ChildIntermittentOutput -> enterState(ParentStateB)
          }
        }

      is ParentStateB -> {
        context.compose(
            childWorkflow,
            input = Bar
        ) { noop() }
        // Other work that leads to enterState(ParentStateA(valueAddFromStateB = something)
      }
```

**Comment by zach-klippenstein** [comment]
That's a pretty serious bug, yikes. How is anything working at all?

Sounds like something in `LifetimeTracker` or `SubtreeManager` isn't cleaning up properly.
