### ISSUE TITLE
[kotlin] Rename compose method and concept in docs to render

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#265]
The `compose` function was originally called `render` in the Swift implementation. After much discussion, we decided to rename to `compose` to avoid suggesting too strong an association with UI (it can return screen data, but can also be any arbitrary value).

However, this is dumb for a few reasons:
 - we're still calling the _type_ `Rendering`
 - "render" is a much more specific verb to represent this specific concept than the super-generic "compose"
 - It turns out Swift never actually got around to renaming everything anyway.

For these reasons, I propose renaming the `State{ful|less}Workflow.compose` method back to `render`.

 - [Slack discussion](https://workflow-community.slack.com/archives/CHB9VKA10/p1554945388058500)
 - Swift issue: #266

**Comment by qrazhan** [comment]
+1 `compose` is really abstract and only leads to more confusion when starting out IMO.
