### ISSUE TITLE
Rename WorkflowContext.compose/render method to composeChild/renderChild

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#267]
It is confusing that both the method you implement (but never call!) and the context method that you call to trigger your children's method are called the same thing. It is difficult to distinguish in the docs, especially since we need to clearly communicate that the former should never be called directly.

To address this, we propose adding a `Child` suffix to the latter method.

 - [Slack discussion](https://workflow-community.slack.com/archives/CHB9VKA10/p1554945388058500)
 - issue for `compose` vs `render` naming: #265

**Comment by rjrjr** [comment]
I take it you're going to follow up and rename both methods to `render` / `renderChild`?
