### ISSUE TITLE
Merge kotlin-1.3.30 branch into master once we're on 1.3.3x internally

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#297]
Since we can't use 1.3.30 internally yet, we have a long-running
branch (kotlin-1.3.30) in the meantime. Once we're on 1.3.3x internally, we can
merge that branch into master.

**DO NOT MERGE until we're using 1.3.3x internally.**

**Comment by 0legg** [comment]
Should be obsolete after #451
