### ISSUE TITLE
Create Workflow sample using command line

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#30]
This is particularly important to demonstrate where the lines between core workflows and platform-and-UI-toolkit-specific concepts are. Text view models/screen data is likely to be a lot simpler than that for GUIs, since there's no concept of "screens".

**Comment by zach-klippenstein** [comment]
It would be cool if we had a sample that shared a reactor between CLI, javafx, android, etc. front-ends. CLI tic-tac-toe?

**Comment by fengdai** [comment]
> It would be cool if we had a sample that shared a reactor between CLI, javafx, android, etc. front-ends. CLI tic-tac-toe?

And Flutter? Workflow (Core) + Flutter (UI) maybe a way to make multiplatform project.
