### ISSUE TITLE
mapRendering might confuse more people than it helps

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#327]
When people who are used to RxJava see `map`, they expect to have a full suite of stream transformation operators available to them. Workflows are not streams, so most stream operators don't make sense.

It is trivial to write a workflow that transforms an output or a rendering, so this operator might just introduce more confusion than it's worth.

[Internal Slack convo](https://square.slack.com/archives/C1MDTM2FR/p1556320353305600?thread_ts=1556319290.302500&cid=C1MDTM2FR)

**Comment by rjrjr** [comment]
Could not disagree more. `mapRendering` is _super_ handy when building composite workflows.

The linked conversation and this ticket are nearly a year old, and I don't believe I've heard echos in that time. Closing this, please re-open if you disagree.
