### ISSUE TITLE
Make RxJava -> Worker API lazy

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#337]
So the current API to use an `Observable` as a `Worker` is an extension function on the former: `myObservable.asWorker()`. This is nice if the observable is simple. However in practice it’s not uncommon chain a bunch of stuff off the source observable before subscribing. In that case, it’s inefficient because you’re allocating all the chain’s operators on every render pass. Changing the API to be lazy might be a good idea.

So instead of:
```kotlin
// This entire chain gets created on every render pass, even though we only
// need when the Worker is started and subscribed to.
fun fooWorker() = service.foo(FooRequest())
  .successOrFailure()
  .observeOn(mainScheduler)
  .firstOrError()
  .asWorker()
```
we’d have
```kotlin
fun fooWorker() = Worker.fromObservable {
  // This block only runs when necessary, when the Worker is being started.
  service.foo(FooRequest())
    .successOrFailure()
    .observeOn(mainScheduler)
    .firstOrError()
}
```

**Comment by vRallev** [comment]
The new approach could be a little more confusing. It isn't clear whether the new observable is cached or is recreated every time when calling `fooWorker()`. But the change makes sense, though.

**Comment by zach-klippenstein** [comment]
True. We should document that thoroughly: the worker will be de-duped purely based on type. If you need to de-dup based on request data, you need to pass an explicit `key` or implement `Worker` yourself.

**Comment by rjrjr** [comment]
Would this replace Observable.asWorker(), or be an alternative to it?

**Comment by zach-klippenstein** [comment]
Replace it.

**Comment by zach-klippenstein** [comment]
@rjrjr [Pointed out](https://github.com/square/workflow/pull/289#discussion_r282297291) that `Deferred<T>.asWorker()` should be removed entirely as part of this.

**Comment by zach-klippenstein** [comment]
I was talking about this with @grantamos yesterday, and realized how much I hate this idea. The API would be super unidiomatic and it's just not worth the effort. If you have an expensive observable, cache it in your workflow or state, or write a custom Worker, otherwise don't worry about it. Closing.
