### ISSUE TITLE
NoSuchFieldException with AtomicReferenceFieldUpdater on Samsung Android 5.0.x devices

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#339]
I haven't seen workflow-specific instances of this crash _yet_, but seems inevitable and so I'm filing this pre-emptively to provide context if/when it pops up (we've seen it internally in other non-workflow coroutines code).

Certain Samsung devices have a bug that affects code using certain atomic primitives. This has been reported in GSON, RxJava, and the coroutines library itself. This is not a library bug, it's a bad runtime. Workarounds at the library level are possible, and are currently being discussed for the coroutines library in kotlin/kotlinx.coroutines#490, but have not been implemented yet.

**Comment by rjrjr** [comment]
No reports.
