### ISSUE TITLE
Make the sample code use kotlinx.serialization for snapshotting chores.

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#34]
Should work, but let's prove it.

**Comment by rjrjr** [comment]
Blocked by #35

**Comment by zach-klippenstein** [comment]
We can't do anything about this until we are using a build system internally that actually works with either reflection or compiler plugins. Moving to post-v1.0.0 backlog.

**Comment by zach-klippenstein** [comment]
I think we can close this. Parcelize/kotlinx.serialization are good enough. WDYT @rjrjr?

**Comment by rjrjr** [comment]
I'll re-purpose this ticket to at least write a sample using kotlinx.serialization.

**Comment by rjrjr** [comment]
Yeah no.
