### ISSUE TITLE
Move to Kotlin 1.3

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#35]
AC: Summary

Blocks:
* #115 
* #113

**Comment by zach-klippenstein** [comment]
I made a long-running branch, [kotlin-13](https://github.com/square/workflow/tree/kotlin-13), so we can do parallel dev and releases for our internal repo while we iron out the kinks.

I also started a [fresh branch](https://github.com/square/workflow/tree/zachklipp/kotlin13) for the actual upgrade.

TODO:
- [ ] Unit tests are failing.
