### ISSUE TITLE
Discuss: Allow "input" to update for a workflow in a `ContainerViewController`/`WorkflowHost`

### ISSUE THREAD

**Issue by davidapgar** [square/workflow#351]
When rendering a child workflow, the "input" (ie: the `Workflow`) is updated each time (allowing it to handle an update to its input, via `workflowDidChange`).

Currently, the root workflow hosted in a `WorkflowHost` (and `ContainerViewController`) does not provide any means to update the `Workflow` - it is just the root workflow, so the outside doesn't have a path to update the input.

We should consider adding this (I believe the Android version *does* have support for this)

**Comment by zach-klippenstein** [comment]
We do, our `WorkflowHost` takes a `ReceiveChannel` (`Signal`) of inputs. Super handy because it also lets the first input be provided asynchronously, which turns out to be a pretty common use case given the way our internal integration works.
