### ISSUE TITLE
Workflow runtime loses events if executing on a non-single-threaded dispatcher or dispatchers.

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#374]
While writing a sample terminal app (#373), I tried running everything on the IO dispatcher. Tons of events got lost. Moving everything to run on a single event loop, from `runBlocking`, fixed the issue (I think).

The problem is that when any part of the workflow runtime is running in parallel with the logic that consumes renderings and feeds events back into those renderings, it's very easy to try sending an event to a rendering in the brief time between when the rendering has been invalidated by another event (e.g. a child workflow being updated by a worker) and the new rendering being published and received by the consumer.

Running everything on a single-threaded dispatcher just avoids this issue.

**Comment by zach-klippenstein** [comment]
I think this might be fixed now, but need to confirm.

**Comment by zach-klippenstein** [comment]
Still need to confirm, but this is not the main use case for 1.0 (which is building UIs), so I'm going to remove from the milestone.

**Comment by rjrjr** [comment]
I believe we fixed this with renderWorkflowIn?
