### ISSUE TITLE
Rx WorkflowHost adapters swallow "Fatal" (as def'd by Rx2) exceptions from subscribers.

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#399]
* Build the Tic Tac Toe app from branch `ray/DNM-swallowed-exception`
* Launch the app and login with a bad password, e.g. foo@bar / pass
* Notice that you hang on the _Loading_ screen when you should pop back to login.

Now uncomment the block at line 47 of `MainActivity`, to make another subscription to `workflowRunner.renderings`. Repeat the recipe, and crash (stack below). 

I suspect that in the hang recipe this exception is being swallowed, but I haven't dug further yet.

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.workflow.ui.backstack.ViewStateCache$prepareToUpdate$2$1" on path: DexPathList[[zip file "/data/app/com.squareup.sample.tictacworkflow-emIWXcG5jN7vKiZo1257Gg==/base.apk"],nativeLibraryDirectories=[/data/app/com.squareup.sample.tictacworkflow-emIWXcG5jN7vKiZo1257Gg==/lib/x86, /system/lib]]
   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by rjrjr** [comment]
The exception is pretty clearly a compiler bug, I'll get that reported. Goes away if I change the UpdateTools interface in  ViewStateCache to a data class -- probably a problem w/anonymous objects in lambdas.

**Comment by zach-klippenstein** [comment]
If I explicitly throw a `RuntimeException` just before running the lambda that triggers this exception, it crashes as expected.

IntelliJ will occasionally suck up all my CPU and hang while stepping around after the `ClassNotFoundException` gets thrown, so that's a good sign.

**Comment by zach-klippenstein** [comment]
I can't repro in a clean room project, and the code that it is occuring in (`flatMapWorkflow`) has been deleted, so I'm going to close this issue.

**Comment by zach-klippenstein** [comment]
I reproduced in unit tests: https://github.com/square/workflow/commit/86b82bcab99b6957af9776125f2459c7c07b7b73

Going to replicate these tests for (our internal-only, for now) `RxWorkflowHost`.

**Comment by zach-klippenstein** [comment]
Working around this internally by checking for this condition and manually passing to the thread's `UncaughtExceptionHandler` if it will be swallowed. 

I've also reproduced the bug in an [isolated project](https://github.com/zach-klippenstein/coroutines-rxflowable-bug-repo) and filed as https://github.com/Kotlin/kotlinx.coroutines/issues/1297.

**Comment by rjrjr** [comment]
Finally got around to reporting this to JetBrains, https://youtrack.jetbrains.com/issue/KT-32351

**Comment by rjrjr** [comment]
@zach-klippenstein we can close this now, yeah?

**Comment by zach-klippenstein** [comment]
I want to leave this open until I'm able to remove our workarounds (I think using Flow should fix).
