### ISSUE TITLE
Proposal: Rename noop() to noWorkflowAction()

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#412]
Just seeing `noop()` inside a lambda is not very readable, you have to remember that it returns a `WorkflowAction`. `noWorkflowAction()` is much clearer.

Compare:

```kotlin
context.renderChild() {
  // Huh?
  noop()
}
```

```kotlin
context.renderChild() {
  noWorkflowAction()
}
```

Not sure this is any better, please comment!

**Comment by rjrjr** [comment]
Yay, a bike shed! I love paint swatches.

I don't like `noWorkflowAction()`, seems verbose. Alternatives:

```
doNothing()
noAction()
stayInCurrentState()
```

I don't actually like the last one,  just putting it up there.
