### ISSUE TITLE
RenderTester should allow expecting child workflows

### ISSUE THREAD

**Issue by davidapgar** [square/workflow#438]
Right now, when using the RenderTester, if a child workflow spawns any workers, the tester will fail (due to it having a separate RenderTesterContext that doesn't expect any workers). This prevents testing against a parent workflow that has a child that spawns a worker in the initial state (ie: a child that "loads" some data).

Paths:
1) Add support for "expecting" a child workflow with controlling what it's rendering is (ie: fail if the child isn't awaited)
2) Allow expectations for the children as well (this becomes more of a gray-box/black-box test, where using the `WorkflowHost` is likely a more accurate simulation.

**Comment by zach-klippenstein** [comment]
In Kotlin, our `RenderTester` is constrained to only test a single layer. We can test that a workflow renders a child, or that a workflow runs a worker, but not that a workflow renders a child that starts a worker. So for this case, I would either write a separate test to verify the child starts its worker, or use the black-box testing machinery. What's your use case?

**Comment by davidapgar** [comment]
The use case is for a workflow that renders a child. However, how it was implemented started the child, which ended up starting the worker on the child - so, this would make it so the children are all simulated instead of being run.

Forces it to test at each layer of the tree.
