### ISSUE TITLE
Use backticks to format test names nicer

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#47]
AC: Test names should ``` `look like this` ```.

**Comment by charbgr** [comment]
@zach-klippenstein I can do that for you! Can I proceed?

**Comment by vRallev** [comment]
PR looks good to me, thanks!

**Comment by charbgr** [comment]
PR is merged. This should be closed

**Comment by zach-klippenstein** [comment]
Yep, in the future I think you have to just say "closes #nn" (the word "issue" confused GitHub).
