### ISSUE TITLE
Guide docs please?

### ISSUE THREAD

**Issue by EtherBit** [square/workflow#478]
When can we expect some good guides? I think it would be super helpful to find issues early on from early adopters.

**Comment by zach-klippenstein** [comment]
I will be getting back onto docs either this week or next!

**Comment by zach-klippenstein** [comment]
First batch of updates were just published. More on the way…

https://square.github.io/workflow/userguide/concepts/

**Comment by EtherBit** [comment]
Thank you Zach! 🎉
