### ISSUE TITLE
Rename LifecycleWorker.onCancelled to onStopped

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#503]
The `onCancelled` name is misleading. It implies that something premature happened (which it didn't), and isn't very parallel to `onStarted`.

Feedback:
> I totally thought since cancelled is there that there were two ways for a workflow to stop.

**Comment by pyricau** [comment]
Btw, might want to also document whether a stopped workflow may be started again.

**Comment by zach-klippenstein** [comment]
@pyricau This issue is specifically for workers – what is unclear about the behavior for workflows? We document pretty extensively that a workflow will start when it's first rendered, and be ~cancelled~ stopped when it's no longer rendered, which implies that if it's rendered again it will be restarted. Or does it?

**Comment by pyricau** [comment]
I hadn't realized this was for workers. Anyway, the general idea is: if you have a lifecycle listener with onStart / onStop, you want to provide documentation on whether you may get onStart calls after onStop, and if yes under which conditions.
