### ISSUE TITLE
testFromStart with SnapShot fails tests

### ISSUE THREAD

**Issue by iankchristie** [square/workflow#538]
I’m upgrading our OnlineBookingWorkflow to v2. In our tests we’re using 
```
workflow.testFromStart(snapshot)

{ ... }
```
It looks like we’re the first people to be using this method with a snapshot and we’re having some issues. We’re getting EOFExceptions (end of file) when we try to read from our snapshot.

It looks like when we call `testFromStart` we create a `WorkflowNode`, which has a `state` as an instance variable. If the snapshot is supplied then it will try to restore the state during initialization. When it restores the state it appears that it expects the buffer to be formatted as so
`[length of parent snapshot][parent snapshot][length of child snapshot][child snapshot]`
But the snapshot that we pass in is only the `[parent snapshot]`. So when we try to collect the [parent snapshot] to parse into a state it crashes since the first 4 bytes in the buffer are `com.`, which is a huge int and tries to read too much. lmk if that makes sense.

The consumers of the method probably shouldn’t be adding those bytes. It seems like `testFromStart` should prepend the length of the snapshot.

**Comment by zach-klippenstein** [comment]
I think the test functions should be explicit about expecting a workflow-specific partial snapshot instead of the output from a render pass, and then wrap the snapshot in an appropriate envelope for WorkflowNodes to process.
