### ISSUE TITLE
Kotlin needs the same behavior as Swift re: Allowing stale renderings' sinks to be reused if subsequent renderings have the same sink types

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#541]
See the idempotence hack in `TodoEditorWorkflow` for an example of why we need this.

**Comment by zach-klippenstein** [comment]
I'm not sure how we can implement this in kotlin - seems like we would to reify the sink type.

**Comment by zach-klippenstein** [comment]
This issue on iOS caused #348, and just caused #541 on Android.

**Comment by 0legg** [comment]
> just caused #541 on Android.

actually caused #627, we're in #541 already

**Comment by zach-klippenstein** [comment]
That's what I get from trying to post these from my phone 🤦‍♂

**Comment by zach-klippenstein** [comment]
This was done in #742.
