### ISSUE TITLE
Swift: change awaitResult(worker …) to running(worker …)

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#544]
Swift and Kotlin have  inconsistent names for this and they're both kind of lame. We've settled on `runningWorker(handler)` for Kotlin, and `running(worker mumble)` for Swift, where `mumble` today is `outputMap`. 

`outputMap` is much more visible to Swift devs than Kotlin devs, so choose whatever works and Kotlin will either follow suit or ignore because it doesn't matter.

Related to #545

**Comment by dhavalshreyas** [comment]
Fixed
