### ISSUE TITLE
[Swift] View Registry to support Factory blocks for screen -> view controller

### ISSUE THREAD

**Issue by davidapgar** [square/workflow#553]
Currently the view registry only supports a screen -> view controller mapping with `register(screenViewControllerType:)` (where the underlying factory is created in that method to instantiate the view controller for that screen).

Previously, there was support for registering an actual factory closure, ie something like:
`register(screenType:, factory: (ViewRegistry) -> ScreenViewController`) (with appropriate generics and all that).

Should consider bringing this back.

**Comment by zach-klippenstein** [comment]
Worth noting that this is how `ViewRegistry` works in Kotlin already.

**Comment by JustinDSN** [comment]
Won't do as we've removed the View Registry in #974.

**Comment by JustinDSN** [comment]
Won't do as we've removed the View Registry in #974.
