### ISSUE TITLE
Need to document clearly difference and use cases for key on worker builder functions vs RenderContext

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#557]
We often get asked why the worker builders all have a key parameter and the `runningWorker` functions on `RenderContext` _also_ have a key parameter. The documentation needs to be much clearer. 

Or, maybe we should get rid of the builder keys entirely and just say "if you need more uniqueness, just implement directly".

**Comment by zach-klippenstein** [comment]
Cc @grantamos

**Comment by davidapgar** [comment]
FWIW in Swift we don't have a key for the `runningWorker` equivalent method (which means we *do* have a gap of not being able to run multiple workers of the same type). Just for context (although it makes me think that running multiple of the same type of worker is something we could consider supporting)

**Comment by zach-klippenstein** [comment]
I'm not sure it's something we actually use for "multiple workers in the same pass". We might use it for "restart worker from previous pass", but again I'm not sure. 

Either way, we could get the same behavior by wrapping the worker with another one that redefines equivalence, although it would be slightly less efficient (but that's fine if it's a super edge case anyway). We just added a `transform` operator (#533) that takes the underlying worker's equivalence into account.

**Comment by zach-klippenstein** [comment]
The core issue was made obsolete by #606 which removed the key on builders. 

The presence of key on runningWorker is still an open question, but I'm inclined to keep it for now because it will make writing unit tests easier since they can match workers on keys (see #489).
