### ISSUE TITLE
Delete Kotlin HelloWorkflow sample? It's dup'd in the bootstrap project.

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#563]
No reason to have it in two places. Should also put a note in the HelloWorkflowFragment sample linking to the template project.

**Comment by zach-klippenstein** [comment]
I think the reason might be that it makes it easy to play with the minimal integration API inline, without publishing snapshot versions. But maybe that's covered enough by the other Android samples we have.

**Comment by rjrjr** [comment]
I'm actually torn about this. Filed the ticket anyway just to remember to think about it again.

**Comment by jshvarts** [comment]
I first checked out the `HelloWorkflow` example (which is great btw) and then cloned the template repo and was a bit disappointed that it's just `HelloWorkflow` app. To me the template repo in its current state has very little reason to exist.

**Comment by jshvarts** [comment]
Not really sure. But given that in Workflow you’d don’t need to extend any framework classes, etc. it’s hard to make a useful template app.

**Comment by zach-klippenstein** [comment]
I think the template repo really wants to be an IDEA project template.

**Comment by zach-klippenstein** [comment]
Bootstrap project is gone.
