### ISSUE TITLE
[Swift] Upgrade to ReactiveSwift 6.0.0

### ISSUE THREAD

**Issue by bencochran** [square/workflow#573]
Allows us to drop the transitive dependency on [Result](antitypical/Result) because of the following Swift 5 features:

* Built-in [`Result`](https://developer.apple.com/documentation/swift/result)
* `Never` conforms to `Error`, dropping the need for `NoError`
* `Error` is self-conforming (thanks to a compiler special-case), dropping the need for `AnyError`

This will be a source-breaking change since it requires changing all `NoError`s to `Never` and dropping a lot of `import Result`s (and maybe others?).

It will also mean Workflow becomes Swift 5+ only.

**Comment by zach-klippenstein** [comment]
This was closed by #574.
