### ISSUE TITLE
Add SignalProducer.asWorker to Swift

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#581]
Context: https://github.com/square/workflow/pull/571#discussion_r318785702

**Comment by zach-klippenstein** [comment]
@davidapgar in the original comment:

> I guess I can see the use case where the isEquivalent would be true for all cases.

In kotlin we take the element type into account here as well. Any reason you wouldn't want to do that?

**Comment by davidapgar** [comment]
> @davidapgar in the original comment:
> 
> > I guess I can see the use case where the isEquivalent would be true for all cases.
> 
> In kotlin we take the element type into account here as well. Any reason you wouldn't want to do that?

I think that makes sense to take that element type into account as well if we got forward with this.

**Comment by dhavalshreyas** [comment]
Done.
