### ISSUE TITLE
Swift: find a better name for mapOutput

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#583]
We met a week or two ago to hammer down some naming issues, and left the room agreeing that swift's `mapOutput` was weak, but uncertain what to change it to. Let's fix that while we still can.

cc @bencochran @zach-klippenstein @davidapgar

**Comment by zach-klippenstein** [comment]
This hasn't come up since, and I think the name is fine personally.

**Comment by rjrjr** [comment]
Yeah, I'd close this.

**Comment by zach-klippenstein** [comment]
FWIW I was planning to also use `mapOutput` in kotlin.
