### ISSUE TITLE
Create Kotlin sample using Litho

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#586]
https://fblitho.com

**Comment by rjrjr** [comment]
Hmm. Not very complementary -- Litho is an entire react-style component library. Under the hood it uses Yoga, which in turn uses ReactNative. 

Meh.

**Comment by colriot** [comment]
@rjrjr sorry to revive an old thread, but it's not correct. RN actually uses Yoga, not vice versa. Yoga is a crossplat Flexbox engine implementation and doesn't care about React or other higher-level frameworks

**Comment by rjrjr** [comment]
Thanks!

**Comment by zach-klippenstein** [comment]
I think this would be about as interesting from a technical integration perspective as integrating with Compose. But i'd rather focus on compose at this point. A litho integration should be possible, but just practically i'm not sure how useful it would be.
