### ISSUE TITLE
Kotlin integration tests reliance on exact renderings is very brittle.

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#598]
Kotlin's `testFromState` and `testFromStart` force you to rely on the exact sequence of renderings that will be emitted from a workflow — but `render` is supposed to be idempotent, and is expected to be called an arbitrary number of times.

An alternative to consider would be something more like expect scripts, probably implemented under the hood as a workflow. The `PropsT` would be a script of expect declarations, probably built with a DSL. Unlike today's system, that forces the tester to consume every rendering in order ever to see output, these could use pattern matching and skip uninteresting renderings.

We could allow lambdas to be hung off various statements to allow assertions to be made against particular renderings or outputs, to push values into mock workers, etc.

http://www.admin-magazine.com/Articles/Automating-with-Expect-Scripts

**Comment by zach-klippenstein** [comment]
This looks like a larger change, bumping to 0.22.0.

**Comment by zach-klippenstein** [comment]
I'm going to not include this in 1.0, since it's a pretty exploratory change and we're unlikely to get to a point where we can deprecate the existing testing API before 1.0.

**Comment by rjrjr** [comment]
Nah, we're good.
