### ISSUE TITLE
Demonstrate Master / Detail navigation

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#61]
AC

 * Master detail navigation via split view container
 * Animated transitions on both left and right
 * Don't worry about config changes yet, that's covered by #29

**Comment by zach-klippenstein** [comment]
I had some thoughts about this I'd written down internally back in February. Not convinced it's a great idea any more but wanted to get them down here just for the record.

----

The above design was done with the old reactor/workflow pool api. V2 workflows fits this sort of compositional problem much better. In particular, we make use of the input parameter to pass data from the supervisor workflow to the master and detail workflows, including selection and rendering hints (master should paint selection state only in split screen, detail should show a back actionbar button only in non-split). We make use of outputs to communicate when something is selected in the master.

We still have a supervisor `MasterDetailWorkflow`. It takes a `MasterWorkflow` and a `DetailWorkflow`. 

**`MasterWorkflow<S> : Workflow<MasterInput, S, MasterOutput, Screens>`**
 - ```kotlin
    data class MasterInput(
      val isSplitScreen: Boolean,
      val backHandler: () -> Unit
    )
    ```
 - `data class MasterOutput<I : Any>(val detailInput: I)`
 - Rendering is a set of screens, which must contain at least a "body" screen that the supervisor puts in the master layer.

**`DetailWorkflow<I : Any, S>:: Workflow<DetailInput<I>, S, Unit, Screens>`**
 - ```kotlin
    data class DetailInput<I : Any>(
      val isSplitScreen: Boolean,
      val input: I,
      val backHandler: () -> Unit
    )
    ```
 - Has no output. If we need to, we could wire up detail output to parent, but I'm not sure there's a use case.
 - Rendering is a set of screens, which must contain at least a "body" screen that the supervisor puts in the body layer.
