### ISSUE TITLE
Dealing with nested navigation

### ISSUE THREAD

**Issue by zoltish** [square/workflow#613]
Hello! 

First of all Id like to applaud all of you for creating this. I think its amazing and I wish I had found it before building something similar myself (actually named it flow too). Ive since then frequented your github page to track your progress and Im a big fan! :)

I hope this is the appropiate place for a question like this, otherwise feel free to point me into the right direction! 

If I understood it correctly, a workflow can render a backstack-screen that holds N screens: the view then pops them in response to back events, and so it goes. Im wondering how you would deal with nested navigation, where one of the N screens in the backstack-screen has its own backstack? 

The case is pretty much: Screen A renders Screen B, which renders Screen C/D/E/F (and screen B should only handle back events for screens D/E/F). Another common scenario Ive noticed is a screen showing a toolbar with a back button; the back events come from the view rather than the system and unless you "hack" a solution where the back event gets redirected to the system - youre left to handle it within your screen (workflow) [1]. How would you approach this? 

Looking forward to hearing your thoughts on this. Keep rocking! 👍 

[1]: Ive experimented with the flow handling the back event, turning it into a state change (pretty much popping the internal top screen) or an output (finished, when there are no more internal screens). This is very cumbersome though, and you end up writing very similar logic over and over again.

**Comment by zach-klippenstein** [comment]
Keeping a stack of screens in your state is the way we do this right now, so I'd say you're on the right track. We haven't actually needed it that often, but I'd expect to factor a lot of common stack management functions out if we did (much like we have with our old navigation library, Flow). [BackStackScreen](https://github.com/square/workflow/blob/master/kotlin/workflow-ui-core/src/main/java/com/squareup/workflow/ui/BackStackScreen.kt) helps support this model.

Another potential technique for doing this, that we haven't actually tried yet, is documented in #411.

Both approaches make nesting backstacks a non-concern – if a workflow that manages a backstack hits an empty stack, it sends an output to its parent telling it so, and the parent can pop its own stack or whatever it needs to do. Handling back events should be the same for app-based buttons and system buttons – all the samples do this.

**Comment by zach-klippenstein** [comment]
Back button handling is also about to become a lot simpler: see #614.

**Comment by rjrjr** [comment]
The tl;dr: comes down to: a back button press is just another event, and an action bar is just another widget. #614 makes it a lot easier to think that way.

**Comment by rjrjr** [comment]
A little more detail: take a look at the `HasModals` interface:

```
interface HasModals<out B : Any, out M : Any> {
  val baseScreen: B
  val modals: List<M>
}
```

That list of modals isn't a back stack, it's a modal stack -- e.g., when you show a modal over a modal over a modal.

For the nested backstacks scenario, the `M` type would be `BackstackScreen<Any>`. The [PanelContainerScreen](https://github.com/square/workflow/blob/master/kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/panel/PanelContainerScreen.kt) demonstrates this (because we'll need exactly this in production ourselves).

I haven't built the proper animation yet, but the idea is that at first appearance of `somePanelScreen.modals[1]`, when we had previous been showing a screen whose modals list was size 1, we'll animate what looks like a new panel opening over the existing one.

Whether that is achieved by opening a dialog over a dialog, or just with animation effects, is TBD. And just an implementation detail to boot.

The workflow(s) that produce these screens are themselves in charge of maintaining the actual back stack. The stuff in the screen objects is just there so that the view system has enough information to choose animations, and to know what view state to preserve.

A child workflow that is producing a backstack flow (B in your example, I guess) can be completely ignorant of whether a parent is nesting it in another flow or not.

I should turn this into documentation or a tutorial, eh?

**Comment by zoltish** [comment]
Thanks for getting back to me!

It kind of makes sense to me now. I didnt see the whole picture view of how BackStackScreens (etc) actually control the navigation earlier on, its pretty neat now that I get it! 

I dont think I fully grasp how a list/detail flow would behave yet though, since that would involve manipulating the render-wrappers directly in the view layer (I think)? E.g. Screen A contains B/C, the view layer has LayoutRunners & Bindings respectively - but LayoutRunner#A would still have to replace its contents for B/C on each new rendering, without creating a new set of views each time around (which I believe the ViewRegistry would do)? Perhaps this is just me not seeing the full full picture of things though - in either case I think doc/tut on the rendering wrappers would be great! :3

**Comment by rjrjr** [comment]
We address that case with pretty pictures in our recent droidcon slide
deck. The list workflow emits output when a selection is made. The parent
workflow turns that into an update of the props in the detail workflow. No
screen-to-screen communication required.

**Comment by zoltish** [comment]
Im with you on that portion of it, and I think it works very nicely! My troubles now are pretty much with how nested renderings would get handled on Androids side of things, I dont see any way around having to manually manipulate the views in order to make it work (which isnt necessarily a bad thing - but from what I can tell it kind of breaks things unless you know your way around the inner workings of how views are automagically bound through the ViewRegistry).

Ill lay out my case, perhaps itll help clarify what Im dealing with. Screen A being the top level screen of the app renders 1 screen (T) that gets shown in its toolbar, and 2 others (B & C) for its content that gets placed inside a FrameLayout.

Binding Screen A is fine, and can be done similar to your samples. Within the LayoutRunners render call though, Im tasked with binding Screen T to the toolbar, and Screen B or C to another View that should get added to a container FrameLayout somewhere in the view. 

This is where I think things fall apart - creating LayoutRunners for T/B/C through the ViewRegistry works, but seems to create new views each time around so Ill need to somehow cache them and keep tabs on whats being shown such that I dont replace the view more than needed (since render gets called quite a bit). Im not sure what the alternative is, but Id say my issue boils down to not being able to really work with the ViewRegistry "magic" for inner views, and not knowing how to deal with them manually. 

Hope that makes sense, and while this is a rather complex scenario with many different screens playing together - I hope its not too far outside the scope of what you want Workflow-UI on Android to be able to deal with! Ive played around with the idea of normalizing the screens to make things easier, but I havent been able to escape it entirely.

**Comment by rjrjr** [comment]
ViewRegistry will always create a new view, that's all it knows how to do.
But the container gets to decide if a new view is needed, and we give help
with that. When the container is showing T', and receives T'', it can call,
say, `toolBarView.canShowRendering(T'')`, and if that's true
`toolBarView.showRendering(T'')`.

You'll see this idiom throughout our container classes, e.g. this fragment
from `ModalContainer`:

```kotlin
base?.takeIf { it.canShowRendering(newScreen.baseScreen) }

    ?.showRendering(newScreen.baseScreen)
    ?: run {
      removeAllViews()
      val newBase = registry.buildView(newScreen.baseScreen, this)
      addView(newBase)
    }
```

BTW, we don't do toolbars that way in our own apps, and this kind of thing
why. In our apps each screen in a flow carries its own toolbar, and we use
animation tricks to make the transition between them mask that fact -- from
the screen's POV, the toolbar is jut another widget. I believe that if you
use TransitionManager that kind of effect is pretty easy to manage.

**Comment by rjrjr** [comment]
ViewRegistry will always create a new view, that's all it knows how to do.
But the container gets to decide if a new view is needed, and we give help
with that. When the container is showing T', and receives T'', it can call,
say, `toolBarView.canShowRendering(T'')`, and if that's true
`toolBarView.showRendering(T'')`.

You'll see this idiom throughout our container classes, e.g. this fragment
from `ModalContainer`:

```kotlin
base?.takeIf { it.canShowRendering(newScreen.baseScreen) }

    ?.showRendering(newScreen.baseScreen)
    ?: run {
      removeAllViews()
      val newBase = registry.buildView(newScreen.baseScreen, this)
      addView(newBase)
    }
```

BTW, we don't do toolbars that way in our own apps, and this kind of thing
why. In our apps each screen in a flow carries its own toolbar, and we use
animation tricks to make the transition between them mask that fact -- from
the screen's POV, the toolbar is jut another widget. I believe that if you
use TransitionManager that kind of effect is pretty easy to manage.

**Comment by rjrjr** [comment]
We should offer a layout that just does that for you, eh?

**Comment by zoltish** [comment]
Knowing that helps a lot! I think the last missing piece of my puzzle is nested dialogs, if I understand it correctly the top level screens being modals automagically creates and shows dialogs (by way of the bindings), but if youre N levels deep and handling some of the binding logic yourself as youve described, youd need to include the "wrapper" view (ModalViewContainer, fx) for a modal container in your layout in order for it to show?

Toolbars: Completely with you on that, this case being my exception due to the "screen" for the toolbar being a timer that takes its own events and such + re-used.

Renderings: Ive seen the ShowRendering logic prior to this chat, but it always seemed like a private api due to there not being any clear guidelines around it. E.g. I wouldnt know that a view built from the ViewRegistry would support any of those methods, and theyre also available on any view. In my own setup Im using something similar to a LayoutRunner, theres no ViewRegistry but if there was, it would return the LayoutRunner rather than the view (which in turn would include the view so that you could add it to some container).

**Comment by rjrjr** [comment]
Just had this exact conversation internally, clearly another place we are
missing docs.

The innermost workflow that wishes to show a dialog declares an explicit
RenderT type like AlertDialogScreenContainer<Any>. Any parent rendering
such a child is responsible — forced by the compiler — for mapping the
child's rendering into its own declared RenderT type, and so on.

You can see this happening in a few of the rendering methods of the Tic Tac
Toe sample.

**Comment by zoltish** [comment]
Ah, I can see it now! Thats an interesting way of handling it, and the view layer automagically dealing with it is a big win (plus, making use of the already registered ViewBindings for the modal screens is sweet). 

I realize this would break the power mentioned above, but have you experimented with or considered flatter screens? As an example, GameFlow would then always render a GameScreen - and the screen would contain all the different fields. Basically containing the fields instead of being wrapped in them. Since were talking about dialogs, it could then contain a Dialog<T> which is Shown(Screen)/Hidden for that purpose; and in the view layer you would create your LayoutRunner<T> and wrap it in a DialogLayoutRunner<T> (similar generics to ModalViewContainer, etc). You lose out on modals just working magically, but you gain full type safety across the board; and creating/binding the dialog is 2 lines of additional code for each dialog (something similar to the ViewRegistry could be built for this too). 

Ive been debating the different approaches over the evening today, so I thought Id share it :3 I think both of them come with their own pros & cons. Feel free to share your thoughts if you like, other than that - thanks a ton for the replies, Ive got a much better understanding of your Workflows and its even more kickass than I had previously grasped!

**Comment by rjrjr** [comment]
Thanks for the great questions. Each answer becomes the seed of a missing
document somewhere, super helpful.

**Comment by zoltish** [comment]
A kind of follow-up question related to nesting again: how are you dealing with nested renderings where state changes occur frequently (e.g. a timer, ticking each second)? 

I can see that a rendering only gets re-created when its state has changed, and that the renderings are diffed before being pushed out to the actual views - but wouldnt this still result in the entire tree of screens (starting from the workflow containing the timer) to be pushed out again? 

```
data class BigScreen(
   val timer: TimerScreen, //Created from TimerWorkFlow
   val content: ContentScreen //Created from ContentWorkFlow
)
```

e.g. BigScreen would get pushed out again every second with a new TimerScreen; 
1) Would ContentScreen be same as the last one pushed out (if any)? So no new calls to render at all for the ContentWorkFlow?
2) And if so, wouldnt this cause issues with re-using an old event-handler?

Thanks again for all the replies! 👍

**Comment by rjrjr** [comment]
Yes, the whole render tree updates every time. So far that does not seem to
be a problem, since we don't do heavy weight things like create views
repeatedly. Although we do rely on view code to be smart about its own
de-duping when deciding whether or not to redraw.

**Comment by zoltish** [comment]
Thanks, that makes sense! 👍

**Comment by zach-klippenstein** [comment]
I'm going to close this issue, but happy to reopen if you have further questions!

**Comment by zoltish** [comment]
Sort of a follow-up! This time Im curious to how you envision handling quite deep hierarchies of screens drawing on top of each other? The logical structure is pretty much as follows:
Top level draws MasterDetails, where the Details may render a Panel with a complex list, tapping a list item should render yet another panel with its details, and opting to edit the details brings up _yet another_ panel. 

Im not sure if it makes sense keeping the screens that way; or perhaps its not really an issue and panels can simply render over each other without any hassle? I fail to see any other way to structure it, but Ive played with the idea of the first panel having a backstack where each subsequent flow is part of; but once you nest further into the hierarchy youd end up with the backstack either containing another backstack or a panel. 

Is there a (simple-ish) way to handle this, or is it a matter of specificity and getting my hands dirty to normalize the nested screens so that they can somehow be placed in one stack, into one panel? Just to make things worse, all of the screens include dialogs - but I believe that can be resolved by simply wrapping the renders in an alert-container? Hoping (*fingers crossed*) that theres a similar solution to this!

**Comment by rjrjr** [comment]
By "panel," do you mean the sample `PanelContainerScreen`? If so, notice that its `modals` field is a list of `BackStackScreen`. None of the samples do this yet, but the idea is to allow it to express panels over panels over panels. The code in `PanelContainer` should handle that already, but I wouldn't be at all surprised to learn that it's buggy.

**Comment by rjrjr** [comment]
We'll be doing exactly that in production real soon now.

**Comment by rjrjr** [comment]
Also notice recent commits adding `plus` operators to both `BackStackScreen` and `MasterDetailScreen`. If what you're actually after is pushing one back stack session on top of another, so that they look like a single set, that should be pretty easy now.

**Comment by zoltish** [comment]
Yup - the one from the samples! Im finding that many of these "issues" I run into are simply a matter of adapting my perspective to the different screen types/wrappers - but your help & seeing the custom viewbindings/screens in the samples has been extremely helpful. 

When you say _"None of the samples do this yet, but the idea is to allow it to express panels over panels over panels."_ do you mean the PanelContainer flattening all the panels (e.g. PanelZ[Panel[A],Panel[B]] into Panel[Z,A,B])? In my world, that would make sense and allow for multiple workflows to render their panels without having to consider the nesting all too much/at all.

**Comment by rjrjr** [comment]
I mean none of them show a modal over a modal yet.

**Comment by zoltish** [comment]
I swear seeing multiple alert-screens being stacked over each other a few days back, but if thats not the case then its just perfect! Ill get to experimenting with the modals this afternoon!
