### ISSUE TITLE
Sample: Implement Redux as a workflow

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#641]
1. Start with a JavaScript redux implementation of a simple redux Todo app or something.
2. Propose a Redux API for Kotlin/Swift, and port the todo sample to it (should be as close as possible to official redux).
3. Implement the redux API as a workflow.

Advanced additional step?

4. Factor out an `ActionWorkflow`, something like this:

```kotlin
abstract class ActionWorkflow<StateT> : Workflow<Unit, Nothing, StateT> {
  abstract fun initialState(snapshot): StateT
  abstract fun render(state, context: RenderContext<Nothing, StateT>): Unit
  
  final override asStatefulWorkflow() = object : StatefulWorkflow<Unit, StateT, Nothing, StateT> {
    override fun initialState(…) = this@ActionWorkflow.initialState(…)
    override fun render(props, state, context): StateT {
      // Need another private child workflow type to bridge this.
      context.renderChild(this@ActionWorkflow, state) { newState → enterState(it) }
      return state
    }
  }
}
```

**Comment by zach-klippenstein** [comment]
Could be a "continuation" of this redux tutorial: https://redux.js.org/basics/basic-tutorial

**Comment by rjrjr** [comment]
Life's too short.
