### ISSUE TITLE
Swift: Match Worker running and Workflow rendering APIs

### ISSUE THREAD

**Issue by bencochran** [square/workflow#649]
When rendering a child workflow, it often looks something like:

```swift
let childRendering = MyChildWorkflow(properties: something)
    .mapOutput { output -> Action in
        switch output {
        case .didComplete:
            return .doneWithTheChild
        }
    }
    .rendered(with: context)
```

whereas for a worker, it looks like:

```swift
context.awaitResult(
    for: SomeAwesomeWorker(properties: something),
    outputMap: { output -> Action in
        switch output {
        case .didComplete:
            return .doneWithTheWork
        }
    })
```

To `Worker` we should add a `mapOutput` and a `running(in: context)` (along with the change to `running` in #544).

After that, we could consider dropping the `render` and `running` methods on `RenderContext` to give only one standardized way to doing those actions.

**Comment by davidapgar** [comment]
This seems like a beneficial change to me - having these be consistent should make this easier to work with.
