### ISSUE TITLE
Issues with Swift samples

### ISSUE THREAD

**Issue by paulofierro** [square/workflow#655]
There are a few issues I ran into when checking out the Swift samples (/swift/Samples)

### 1. Build issues
[The `Tutorial` app readme](https://github.com/square/workflow/tree/master/swift/Samples/Tutorial) states you need to run the following:

1. `bundle install`
2. `bundle exec pod install`
3. Open `Tutorial.xcworkspace`

Unfortunately the Tutorial scheme does not build in Xcode 11.1 (11A1027), due to errors such as:
`No such module 'Result'` and `Use of undeclared type 'NoError'`

I get the same errors in the TicTacToe app. The SampleApp has no build issues.

### 2. Tutorial Tooling issues
The [first chapter of tutorial](https://github.com/square/workflow/blob/master/swift/Samples/Tutorial/Tutorial1.md) also mentions creating a new file using Xcode templates, unfortunately it doesn't mention that these first need to be installed nor how this is done. This is covered in the [Tooling readme](https://github.com/square/workflow/blob/96ce04cf56caba25d024a26c0da94ddcf7ca1355/docs/tutorial/tooling.md), so a link to it should do the trick.

**Comment by zach-klippenstein** [comment]
From @davidapgar:

>  It looks like the samples and tutorials weren’t updated when the ReactiveSwift 6.0 update landed - all of them (and the templates) will need to be updated to no longer import (and use) the “Result” dependency
>  It should be a fairly mechanical change at least, just a bit time consuming with updating the tutorials

**Comment by paulofierro** [comment]
There's one tiny build issue left in the TicTacToe app:

`Type 'AuthenticationWorkflow.AuthorizingEmailPasswordWorker' does not conform to protocol 'Worker'`

In `AuthenticationWorkflow.swift`, both `AuthorizingEmailPasswordWorker` and `AuthorizingTwoFactorWorker` use the following method signature for `run`:

```swift
func run() -> SignalProducer<Output, NoError>
```
Using Xcode's fixit changes this to:
```swift
func run() -> SignalProducer<AuthenticationWorkflow.Action, Never>
```
which builds 👌

**Comment by paulofierro** [comment]
Apologies, you can ignore the above. It looks like the TicTacToe sample app wasn't updated in #663.

**Comment by zach-klippenstein** [comment]
Awesome, thanks @paulofierro!
