### ISSUE TITLE
Make Todo sample master/detail on tablets

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#660]
Requested: https://kotlinlang.slack.com/archives/C5HT9AL7Q/p1570716327013500?thread_ts=1570487716.042800&cid=C5HT9AL7Q

**Comment by rjrjr** [comment]
* From Workflow POV, always MD
 * Detail slot in screen is nullable
 * Single view hides master if detail is full
 * split view sends event asking for initialDetail
 * separate events for close detail (used only by single) and exit (used by both)

**Comment by zach-klippenstein** [comment]
This is basically a clone of #61, but I'll leave that issue closed since this one is specific to the Todo sample app. I've commented on that issue with some thoughts I had back in February about a generic master/detail approach, but I don't think it's a very good idea anymore.
