### ISSUE TITLE
Proposal: Tree-shaped BackStackScreens

### ISSUE THREAD

**Issue by bencochran** [square/workflow#676]
Right now BackStackScreen is essentially:

```swift
struct BackStackScreen {
     var items: [Item]
}
```
(where `Item` is basically a screen)

This work well for flat stacks, but means that if I want to push the details of a sub-flow down into a child workflow, I have to manage the concatenation of those screens myself. It also means that protecting from an empty list of items happens as a runtime assertion rather than being modeled in the type itself.

Back in the original iOS architecture discussions, the following basic shape was proposed:

```swift
struct BackStackScreen {
     var first: Item
     var subsequent: [BackStackScreen]
}
```

(ignore those particular spellings probably?)

For one, this lets me guarantee at compile time that someone rendering a BackStackScreen has at least one screen for me. It also allows me to nest child flows without reshaping the stack myself.

When it comes time to install this stack into a view, the flattened stack would be a depth-first traversal of this tree:

```swift
extension BackStackScreen {
    var flattented: [Item] {
        return [item] + subsequent.flatMap({ $0.flattened })
    }
}
```

------

**Alternative:** We could also simplify the composing of today’s `BackStackScreen`s by adding a convenience `func appending(backStackScreen: BackStackScreen)` and doing the concatenation in there. But it leaves the fact that as far as my code is concerned, I need to deal with the fact that the overall list of items _could_ be empty. (Also, on iOS inside Square today this is tricky because we still have support for implicit BackStackScreens, oops).

**Comment by rjrjr** [comment]
WRT implicit, @AquaGeek is in the process of ripping that out, I think we can ignore for this conversation.

That's pretty similar to today's Kotlin `BackStackScreen`, except that the top / rest are just projections from the underlying list, basically the following (elides some convenience constructors):

```
data class BackStackScreen<StackedT : Any>(
    val stack: List<StackedT>
) {
  init {
    require(stack.isNotEmpty()) { "Empty stacks are not allowed." }
  }

  val top: StackedT = stack.last()
  val backStack: List<StackedT> = stack.subList(0, stack.size - 1)
}
```

That seems simpler to me — I treat the thing as a list a lot more often than I give special treatment to `0`, and I'm still protected from empty stacks.

WRT flattening, I'm starting to think that what I really want is something to inline nested BackStackScreen children — maybe right in the constructor, maybe as a transforming function. I don't want parent containers that are assembling child renderings to be forced to be aware of whether the children are giving BackStacks or not. (I suspect your `item` / `subsequent` structure would make that harder, not simpler.)

Presuming #674 gets merged, I'll follow up w/a sample that illustrates the use case I have in mind, see if it's actually useful.

**Comment by bencochran** [comment]
The Kotlin convenience properties are similar, but rather than `first + rest` are `previous + top`. But that’s mostly inconsequential here. The main difference is that my proposed shape doesn’t have to have that assertion. It’s impossible to construct an empty stack.

Not sure exactly how this works on Android, but for us, our children are often responsible for handling their own back buttons (often by sending an output back to us). This means they need to end up in the same stack as the parent’s rendering. I definitely don’t want to make a `BackStackScreen` conditionally handle some children differently at runtime (e.g. via a runtime type check). Which means I need to know that child renders a back stack item.

I think I need to play around more to develop my thoughts further. But I’d love to avoid magic behavior based on certain types when possible (see also us not handling going from a modal container rendering to a non-modal being an atomic swap just like any other screen type change).

**Comment by rjrjr** [comment]
This will be an easier discussion around a whiteboard.

**Comment by rjrjr** [comment]
I'm going work on my coalescing idea today, will avoid making it implicit the way I described above. I'll give your shape a try at the same time. E.g.

```kotlin
data class BackStackScreen<StackedT : Any>(
    val bottom: StackedT,
    val backStack: List<StackedT>  = emptyList()
) {
  val top: StackedT = stack.last()
  val backStack: List<StackedT> = listOf(bottom) + backStack
}
```

Still thinking about the best way to allow coalescing without forcing a parent screen to know whether or not a child is emitting back stacks itself, without being too magical about it. I still think that's important, and don't see that it conflicts at all with subscreens handling back events themselves -- we often do that as well.

This is the bit of the conversation that would be so much easier face to face, but I'm clearly never going to breath the same air as you again to get around a white board (plumber!) so I'll put up a sample instead.

**Comment by AquaGeek** [comment]
I'm tempted to follow [`NonEmpty`'s approach](https://github.com/pointfreeco/swift-nonempty/blob/51391d699413a13feefbf81b16287b773d2abd38/Sources/NonEmpty/NonEmpty.swift#L7-L10) and remove the argument labels (which also collapses the single-value initializer into the second one).

**Comment by rjrjr** [comment]
Looks parallel to where I landed in Kotlin, and I'm really happy with that. 

I'd suggest a couple of additions that are already carrying their weight for me:

```swift
    public init(backstack: [Item], top: Item) {
        items = backstack + [top]
    }
```

And convenience properties paralleling the various init arguments -- that is, `top` and `backstack` in addition to `items`.

We should also try to land on consistent naming, but let's not block this PR for that bikeshed.

**Comment by JustinDSN** [comment]
@bencochran is this ticket already done?

**Comment by zach-klippenstein** [comment]
@bencochran @rjrjr I think this is done, please re-open if you disagree.
