### ISSUE TITLE
[iOS] If 2 signals fire in the same run loop, the second is ignored

### ISSUE THREAD

**Issue by bizzemfrog** [square/workflow#744]
If a workflow is subscribed to 2 signals, when both signals send a value in the same runloop, the second signal's value is ignored.

What I have observed is that the both of the signal's map closures get called (ie `context.subscribe(signal: signal.map { Foo -> Action in ... })`) but only the fist emitted action gets `apply` called on it. 

Under the hood I see both actions get enqueued in the `WorkflowNode.SubtreeManager.Subscriptions`' Pipe but once the fist action is applied, the context is reset, which invalidates the `Subscriptions`' Pipe, causing the queued event to get dropped.

I wouldn't expect a signal's value get ignored, and I wouldn't expect developers to ensure that signals don't fire in the same run loop. Seems like subscription events should get queued in a system apart from the current render context.

**Comment by dhavalshreyas** [comment]
@bizzemfrog pushed a branch with a failing test to help investigate this issue:  https://github.com/square/workflow/commit/ee284f3b1bcd2c19daee4791e5ca3af0a357b79d

To help with exploration, I have a rough version of the fix: https://github.com/square/workflow/commit/970931366218627d803d8b38f5060e5509513fa3

I'm now trying to figure out what the right/clean fix for this should be. @davidapgar has some excellent analysis and documentation for a similar issue here: https://github.com/square/workflow/issues/348

I'll be digging into this next week, meanwhile if anybody has any ideas/suggestions, it'll be much appreciated 🙏🏼

**Comment by AquaGeek** [comment]
#1025 Should fix this

**Comment by dhavalshreyas** [comment]
#1048 fixes this.
