### ISSUE TITLE
Android CI is broken

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#759]
The android shard for PRs over the last couple days have all been erroring out.

For now, **if you're merging a non-Kotlin/Android PR**, you should go ahead and merge if only the Android shard fails.

**Comment by zach-klippenstein** [comment]
Cause is we time out waiting for the `android-wait-for-emulator` command.

Removing the run-in-background ampersand in the travis file (#758) shows the emulator command fails because it can't find a file:
```
78.43s$ emulator -verbose -avd test -no-accel -no-snapshot -no-window -no-audio -camera-back none -camera-front none -selinux permissive -qemu -m 2048
statvfs('/home/travis/.android/avd/test.avd/snapshots/default_boot/ram.img') failed: No such file or directory
emulator: ERROR: AdbHostServer.cpp:102: Unable to connect to adb daemon on port: 5037
/home/travis/.travis/functions: line 109:  4717 Segmentation fault      (core dumped) emulator -verbose -avd test -no-accel -no-snapshot -no-window -no-audio -camera-back none -camera-front none -selinux permissive -qemu -m 2048
The command "emulator -verbose -avd test -no-accel -no-snapshot -no-window -no-audio -camera-back none -camera-front none -selinux permissive -qemu -m 2048" failed and exited with 139 during .
```

**Comment by zach-klippenstein** [comment]
@phoenixuprising suggested this can be caused by running out of memory.

Confirmed with @rjrjr offline, I'm going to disable instrumentation tests in CI for release branch so I can roll out some fixes, and then continue investigating on master.

**Comment by zach-klippenstein** [comment]
Some ideas to try:

* [ ] Reduce memory config of emulator
  * Same error.
* [ ] Enable sudo to disable containerization (I think support for this was recently discontinued?)
  * Same error.
* [ ] Change emulator SDK version.
* [ ] Set `dist: trusty`, which is [apparently required](https://docs.travis-ci.com/user/languages/android/) even though we've (never?) done it.

**Comment by zach-klippenstein** [comment]
Build is broken even on the first commit that introduced instrumentation tests: #767

**Comment by zach-klippenstein** [comment]
Enabling sudo and explicitly setting the `dist` to `trusty` didn't work: #768

**Comment by zach-klippenstein** [comment]
The first time we observed this issue was on [Nov 15th at 17:06, on one of @JustinDSN's builds](https://square.slack.com/archives/CE470RL5T/p1573866376162800).

**Comment by zach-klippenstein** [comment]
I've spent about a week on this, so I'm going to timebox and just disable the instrumentation shard.

**Comment by zach-klippenstein** [comment]
We have a support ticket with Travis about this: https://support.travis-ci.com/hc/en-us/requests/12924

**Comment by zach-klippenstein** [comment]
@pyricau might have found a fix: https://github.com/square/leakcanary/pull/1665

**Comment by aleenajoseph993** [comment]
Hi @zach-klippenstein 
I m facing the following error while building my first app in Android studio. Adbhostserver cpp:102, Unable to connect adb to daemon on pprt 5037

Please help me solve this.

**Comment by zach-klippenstein** [comment]
This looks like a local dev environment issue. If you have some reason to suspect this library is causing the error, please file a separate issue.
