### ISSUE TITLE
kdoc and sample code needed for Worker

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#81]
AC

- [x] `rx2.Reactor` kdoc covers them as well
- [x] core `Reactor` kdoc covers `Worker`
- [x] Sample code uses `rx2.asWorker` and `rx2.workerResult`

**Comment by zach-klippenstein** [comment]
@rjrjr There is _some_ sample code using it already: https://github.com/square/workflow/blob/730d356c52d491ddbb06e74da98a931db70afdbb/sample-game-common/src/main/java/com/squareup/sample/tictactoe/RunGameReactor.kt#L67
https://github.com/square/workflow/blob/730d356c52d491ddbb06e74da98a931db70afdbb/sample-game-common/src/main/java/com/squareup/sample/tictactoe/RunGameReactor.kt#L115
Should we add a more complex sample? The

**Comment by rjrjr** [comment]
Nah, that was the main thing I didn't want to forget about.

**Comment by zach-klippenstein** [comment]
Rx2 `Reactor` kdoc covers workers as well:
![image](https://user-images.githubusercontent.com/101754/50368919-9c504f00-0542-11e9-817b-0c9ddcf55fcf.png)
