### ISSUE TITLE
Simplify Kotlin WorkflowAction

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#812]
This is a simpler alternative to #644.

`WorkflowAction` is nice conceptually, but its Kotlin incarnation still requires too much ceremony. A handful of fixes should go a long way to streamlining its use:

- [ ] Eliminate `EventSink`, and instead make `RenderContext` itself the sink. (Or at least make `RenderContext` implement the interface itself, s.t. we can preserve `contramap` and such.)
- [x] Instead of returning the output value, give `Mutator` an output field that defaults to null. (Take care to disallow setting it to null.)
- [x] Give `StatelessWorkflow` the same workflowAction extension that `StatefulWorkflow` has
- [x] ~Provide a ktlint check that warns when event handler lambdas do anything other than call `context.update`~ (moved to #834)

**Comment by zach-klippenstein** [comment]
Example:
```kotlin
class MyWorkflow : StatelessWorkflow<Foo, Bar, Baz>() {
  override fun render(
    props: Foo,
    context: RenderContext<Nothing, Bar>
  ): Baz {
    return Baz(
      onSelect = { selection -> context.update(myAction(selection)) }
    )
  }

  private fun myAction(selection: String) = workflowAction {
    analytics.log(MyEvent)
    output = Selected(selection)
  }
}
```

**Comment by afollestad** [comment]
Excited for this to land in SPOS 👏
