### ISSUE TITLE
[Swift] Proposal: Remove ViewRegistry

### ISSUE THREAD

**Issue by dhavalshreyas** [square/workflow#815]
# [Swift] Proposal: Deprecate ViewRegistry

* Discussion: #390
* Authors: @bencochran, @dhavalshreyas
* Status: Proposal

## Overview
This issue proposes:
* Deprecating `ViewRegistry` in favor of expanding the `Screen` protocol to help build and update the `ViewController` to be rendered.
* Not requiring the rendered `ViewController` to inherit from `ScreenViewController`.

## Background & History
Currently, for a `Screen` type to be rendered, a view factory must first be registered using `viewRegistry.register(screenType:factory:)`.

This mapping can be easily missed during development and will throw a `fatalError` when a screen render is attempted.

`ViewRegistry` also requires the provided factory to return a `ScreenViewController` type.  `ScreenViewController` has a defined `initializer` and a `update(screen:)` method defined, which helps `ViewRegistry` build and update the `ViewController` as required. However, projects which already have a `BaseViewController` that all `ViewController`s are required to inherit from will have a tough time adopting `Workflow`.

## Goals
* Help make the `Workflow` APIs simpler and clearer.
* Provide a more flexible API to describe a `ViewController`.

## Non-Goals
> TODO

### 1. Introduce ViewControllerDescription

`ViewControllerDescription` is a struct which describes how to `build` and `update` a `ViewController`.

```swift
ViewControllerDescription(
    builder: { NewViewController() },
    updater: { viewController in
      viewController.update()
    }
)
```

### 2. Add `viewControllerDescription` property requirement to `Screen`
Introduce a property requirement on `Screen` protocol that returns `ViewControllerDescription`.

```swift
protocol Screen {
    var viewControllerDescription: ViewControllerDescription { get }
}
```

This lets us render `WelcomeScreen` using `WelcomeViewController` by adding:

```swift
extension WelcomeScreen: Screen {
    var viewControllerDescription: ViewControllerDescription {
        ViewControllerDescription(
            builder: { WelcomeViewController(screen: self) },
            updater: { $0.update(screen: self) })
    }
}
```

### 3. Remove `ViewRegistry`
Since each `Screen` can now describe how to both create and update a rendered `ViewController`, we will no longer need `ViewRegistry` and it can now be removed.

> **Related**: Requirement for a rendered `ViewController` to inherit form `ScreenViewController` will also be removed.

## Trade-off
This implementation will require the `Screen -> ViewController` mapping be defined at compile-time instead of run-time. Implementations which relied on being able to pick this mapping during run-time will no-longer be able to do so. 

### Work-arounds
A couple of work-arounds:
* Provide the `Screen` conformance in a different library, which can be swapped during compile-time.
* Wrap a `Screen` with another type, which can then provide a `ViewController` for rendering during run-time.
> **Example**:
> ```swift 
> struct StyledScreen<S: Screen>: Screen {
>   let screen: S
>   let viewControllerType: UIViewController 
> }
> ```

## Kotlin
As @rjrjr explains here https://github.com/square/workflow/issues/390#issuecomment-561900842, we cannot make a similar change in Kotlin yet. `ViewRegistry` will continue being used there.

## Effect on API
Fully implemented this change will introduce breaking API changes.

* `ViewRegistry` will be deleted and all the call-sites will need to remove it's usage.
* All `Screen` types will need to add the `viewControllerDescription` implementation.

> Example:
> **From**
> ```swift
> extension ViewRegistry {
>    func registerWelcomeScreen() {
>        register(screenViewControllerType: WelcomeViewController.self)
>    }
> }
> // Call `viewRegistry. registerWelcomeScreen()` before the screen is rendered.
> ```
> 
> **To**
> ```swift
> extension WelcomeScreen: Screen {
>    var viewControllerDescription: ViewControllerDescription {
>        ViewControllerDescription(
>            builder: { WelcomeViewController(screen: self) },
>            updater: { $0.update(screen: self) })
>    }
> }
> ```

## Migration
Several migration approaches have been discussed. These include:
1. Introduce an intermediate version which adds the new concepts without any breaking changes and follow-up with the breaking API changes.
2. Introduce a new `WorkflowUI` target which will allow adopters to switch over to the new API on their own timeline (@JustinDSN).
3. A hard-migration which introduces all changes in one-go.

We would like to explore a migration path that allows for a safe, gradual migration from `ViewRegistry` to `ViewControllerDescription`. We're currently considering options 1 and 2.

## Alternatives considered
Several alternatives were proposed in #390 including https://github.com/square/workflow/issues/390#issuecomment-498783829, https://github.com/square/workflow/issues/390#issuecomment-498922765

**Comment by dhavalshreyas** [comment]
Hello! 

This proposal template has been borrowed from [`swift-evolution`](https://github.com/apple/swift-evolution/blob/master/proposal-templates/0000-swift-template.md). 

Please consider these while responding:

* What is your evaluation of the proposal?
* Is the problem being addressed significant enough to warrant a change?
* Does this proposal fit well with the feel and direction of `Workflow`?
* If you have used other libraries with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?

All comments and feedback are appreciated!

- Dhaval

**Comment by rjrjr** [comment]
Please add an explicit discussion of the ability to use of protocol extensions to allow decoupling, and the trade offs implied (e.g., a single set of bindings per application, e.g. implications for customizability of workflow based libraries).

Should also discuss how to apply this to existing samples, tutorials, libraries -- especially any stock or sample screen classes.

**Comment by dhavalshreyas** [comment]
@rjrjr: Updated based on your feedback, let me know if that addresses it.

**Comment by rjrjr** [comment]
Should state an explicit goal of retaining the ability to decouple screens from related ViewConroller code -- that is, it must continue be possible to implement screens and related workflows in libraries with no dependency on UiKit.
