### ISSUE TITLE
Reconcile user events and worker outputs

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#824]
Right now user events get pushed into sinks (or into the RenderContext once #812 lands), while worker output return a WorkflowAction. While the latter is nicely foolproof, the inconsistency between the two types of inputs is jarring.

We should instead change the return type of the worker lambdas to `Unit`, and have them push into the sink / context the same way that user events do.

**Comment by rjrjr** [comment]
Migration will be a drag thanks to the jvm's limitations. Perhaps we should add a new method `running` that deprecates `runningWorker`?

**Comment by zach-klippenstein** [comment]
Discussed offline, and we don't think we can improve on the current API. Using the sink for workers means we could get worker actions executed after a render pass causes a worker to be torn down, which is better to avoid.
