### ISSUE TITLE
Make RenderContext the receiver in the `render` method.

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#836]
Maybe this is for Kotlin only? I think we should change the signature of the Workflow `render` to methods to be extensions on `RenderContext`:

```kotlin
fun RenderContext.render(
    props: PropsT,
    state: StateT
): RenderT
```

Especially after the changes describe in #812 land, so that we can just say `sendEvent()`, `renderChild()`, `runningWorker()` with no further qualification.

**Comment by SalvatoreT** [comment]
It would definitely make the syntax nicer, but I could also see it confusing folks when they reference the context a second time unknowingly and having everything blow up in their face.

**Comment by zach-klippenstein** [comment]
> reference the context a second time unknowingly

What do you mean?

**Comment by SalvatoreT** [comment]
If you call `sendEvent` within the handler of the `runningWorker`, (I think) you'll have a problem.

**Comment by rjrjr** [comment]
Yeah, but we plan to fix that, #824.

**Comment by SalvatoreT** [comment]
> Yeah, but we plan to fix that, #824.
Oh cool! I'm not as versed in the roadmap, and my perspective is mostly based in what's currently live.

The only other thing that jumps out (in my few minutes of thinking about the problem) is that this will make the Workflows less fun for folks who want to use it from Java. I don't if that's out of scope for this project.

**Comment by rjrjr** [comment]
We pretty much take for granted that this library is a nightmare for Java devs.

**Comment by SalvatoreT** [comment]
Either way, I'm a fan of making the `context` explicit so you know what you're calling. If you want to avoid typing as much, you can surround your whole `#render` method in this.

```
context.run {
  // renderChild(...) or something
}
```

**Comment by zach-klippenstein** [comment]
Chatted offline, we're going to leave as-is.
