### ISSUE TITLE
Swift builds started failing compilation 

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#838]
Started in the last build of #837 :

```
/Users/travis/build/square/workflow/swift/Samples/TicTacToe/Pods/ReactiveSwift/Sources/FoundationExtensions.swift:88:3: switch covers known cases, but 'DispatchTimeInterval' may have additional unknown values, possibly added in future versions
                switch self {
                ^
```

This is a weird error, this PR didn't touch anything swift-related but this looks like a legit compilation error.

Build job: https://travis-ci.com/square/workflow/jobs/269041643

cc @AquaGeek @dhavalshreyas @AquaGeek @timdonnelly @bencochran

**Comment by dhavalshreyas** [comment]
Looks like it was a transient issue? The builds are green again: https://travis-ci.com/square/workflow/jobs/269176088
