### ISSUE TITLE
Delegating interface is too confusing

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#87]
Perhaps it should be called WorkflowTicket, and perhaps it can be a struct rather than an interface. So, instead of

```kotlin
  internal data class Playing(override val delegateState: Turn) : RunGameState(),
      Delegating<Turn, TakeTurnsEvent, CompletedGame> {
    override val id = TakeTurnsReactor::class.makeWorkflowId()
  }
```

maybe something like

```kotlin
  internal data class Playing(
    val takingTurns: Ticket<Turn, TakeTurnsEvent, CompletedGame> ) : RunGameState()
```

And perhaps `awaitNextDelegateReaction` is changed to include the updated `Ticket` every time.

Also need doc, examples of parallel child workflows (master / detail, picker grid, status bar...). Two point of confusion:

 * How do you hang multiple `Delegating` / `Ticket` off of single parent
 * If workflows only run once and emit one result, how do you keep, say, the picker grid running a long time.

These are known and simple, but not easy to discover.

**Comment by loganj** [comment]
... and rename `awaitNextDelegateReaction`?

**Comment by rjrjr** [comment]
Clearly.
