### ISSUE TITLE
renderTester API should support verifying that render event did not send to sink

### ISSUE THREAD

**Issue by ijwhelan** [square/workflow#885]
I have a workflow and I want to test that when I'm rendering a certain state, that no actions were processed when the user submits invalid data.

Right now, `RenderTestResult` has `verifyAction()` and `verifyActionResult()` methods, but there isn't an easy way to verify that there was no action.

A `verifyNoAction()` method would be helpful for testing this kind of workflow.

**Comment by zach-klippenstein** [comment]
What you mean by "no actions were processed"? If the "user" has "submitted" data (either through a rendering event, worker, or child workflow), then some action will always be processed.

If you mean that the action didn't do anything, then you can either write a separate test for your action, or use `verifyActionResult` to assert that the state wasn't changed and no output was emitted. If your action may potentially perform side effects, then you could, for example, use Mockito to verify that your side effect mocks weren't interacted with.

We could provide a `verifyNoAction` method that would check that the state didn't change and no output was emitted, but I'm not sure that's better than being explicit. Maybe it just needs a better name.

**Comment by zach-klippenstein** [comment]
Chatted offline, the behavior that we need to assert is that a rendering event is a no-op that doesn't actually send to the sink.
