### ISSUE TITLE
Remove AndroidX appcompat dependency from main workflow-ui-android module

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#905]
This support depends on AndroidX's `AlertDialog`, but some consumers internally don't want to depend on this artifact and aren't using alert dialogs at all.

cc @rjrjr @Armaxis

**Comment by rjrjr** [comment]
I'd be fine with leaving it here and dropping the AndroidX dep. It's so trivial to fork this and build your own alert.

**Comment by rjrjr** [comment]
Discussion: https://workflow-community.slack.com/archives/CHTFPR277/p1579804738002100

**Comment by rjrjr** [comment]
Related: #833

**Comment by rjrjr** [comment]
Proposal is to move things to this structure, and to ditch the default bindings (#833) entirely.

```
workflow-ui-backstack:common
workflow-ui-backstack:android
workflow-ui-modal:common
workflow-ui-modal:android
```

**Comment by zach-klippenstein** [comment]
Closing in favor of #915.
