### ISSUE TITLE
[swift] Remove all project files for Swift implementations

### ISSUE THREAD

**Issue by dhavalshreyas** [square/workflow#930]
1. Use `cocoapods-generate` to generate the project files.
2. Update .travis.yml to gen projects on CI
3. Delete .xcodeproj project files

**Comment by amorde** [comment]
Initially we were considering migrating the Tutorial project to `pod gen`, but I think we should keep it as-is for two reasons:

1. Engineers don't work on the tutorial often, so merge conflicts in the project file are not likely to be an issue
2. It helps for people new to the project to be able to open a workspace and get started quickly, without having to use `pod gen`. Only `pod install` is required.

Going to close as complete, but we can open another issue if we think the tutorial needs to be migrated as well.
