### ISSUE TITLE
Static site CI shard is broken 

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#951]
Somehow Travis started trying to use Python 2.7 instead of Python 3.6, causing `pip install mkdocs-material` to start failing.

[Last successful build, on master](https://travis-ci.com/square/workflow/jobs/285671784):
![image](https://user-images.githubusercontent.com/101754/74207077-e3ac0a00-4c32-11ea-92ef-cad1fbbbf1a4.png)

[Failed build](https://travis-ci.com/square/workflow/jobs/285717015):
![image](https://user-images.githubusercontent.com/101754/74207096-f32b5300-4c32-11ea-985a-d8e39ab9b116.png)

**Comment by zach-klippenstein** [comment]
Oh, @JustinDSN fixed this on master already, this just affects old branches: https://github.com/square/workflow/commit/c28c3ad6776b89fa281ded561048e0ae37b52258

**Comment by JustinDSN** [comment]
I fixed this in master and @zach-klippenstein fixed this in the release branches.
