### ISSUE TITLE
RenderTester API should not require explicitly expecting all workers 

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#959]
[Internal Slack discussion](https://square.slack.com/archives/C1MDTM2FR/p1581085074142600?thread_ts=1581033959.140600&cid=C1MDTM2FR):
> Feature request, by the by: in terms of future-proofing the tests,  can it be that "unexpected" renders and workers are treated as non-triggering no-ops?  I see some advantage to having to make them explicit, but it does mean my test is now sensitive to changes for code paths I'm explicitly not testing...

We could make workers “expected” by default, but we can’t automatically expect child workflows, since `renderChild` must always return a rendering and the test library can’t know how to construct your childrens’ renderings for you.

**Comment by wugeorgeq** [comment]
Is this still a good first issue if I want to start contributing? :)

**Comment by zach-klippenstein** [comment]
Thanks for putting up a PR @wugeorgeq! I just noticed it now, my bad. Would like to get agreement from a few more maintainers before merging it though. cc @rjrjr @bencochran @dhavalshreyas

**Comment by rjrjr** [comment]
If we make this change, do we have a way to express "expect this worker and no other"? That seems important.

**Comment by bencochran** [comment]
Maybe we could instead make this opt-in? Like a “allow unexpected workers” flag of sorts? That would a) make the default still break if you go from no workers to workers unexpectedly and b) give a way to expect some but ignore other workers.

**Comment by zach-klippenstein** [comment]
So we agree this is a good option to have, it's an open question which is the better default behavior.

I think the default should be more lenient. The original reason this came up was because someone added a worker to a workflow, and immediately a bunch of completely unrelated tests broke. I don't think that's a good UX, and if we make strictness opt-out, nobody's going to remember to do that and we will only have solved half the problem. Strictly expecting "no other workers" is useful but is a specific assertion, and more brittle, and so it should be opt-in. 

For comparison, Mockito (popular java mocking library) has similar functionality for verifying methods calls on a mock by either calling the `verifyNoMoreInteractions` for the catch-all case — it is also opt-in.

**Comment by rjrjr** [comment]
I'm fine with lenient by default, so long as I have a way to turn
strictness on.

**Comment by wugeorgeq** [comment]
Sorry for the late reply, I'll make an attempt unless there are objections :)

**Comment by wugeorgeq** [comment]
> The fact that we had to break out a separate function for workers is weird. Why does it make sense to allow leniency for workers but not for workflows?

@rjrjr brings up a good point in https://github.com/square/workflow/pull/1084, should we make leniency the same for child workflows? It feels like the answer is no because we certainly want to force assertions of new renderings. The part that's confusing for me is that it seems like it'd make sense to allow leniency for side effect workers but perhaps not workers that trigger a state change/action? Should we specifically only allow leniency for `Worker<Nothing>` or is that just confusing?

**Comment by wugeorgeq** [comment]
Oh wait, or was the comment just about keeping the generic method rather than having 2 methods? :D

**Comment by rjrjr** [comment]
No, that was just what made me notice it.

I don't see a reason to distinguish between side effects and other workers, just seems confusing to me. But I also don't see a reason to be strict with workers and not strict with children, unless there's some structural reason we have to.

Zach's still on vacation. I think he should have the final word here when he gets back.

**Comment by zach-klippenstein** [comment]
If we're not strict with children, how do we produce the child renderings for the workflow-under-test?

**Comment by rjrjr** [comment]
There it is, I figured I was missing something.

LGTM
