### ISSUE TITLE
Give Worker an key property instead of automatically using type + equivalence

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#961]
Currently, worker's are deduped based on both type parameter and the result of comparing them with `isEquivalent`/`doesSameWorkAs`. This requires each WorkflowNode to do linear searches over its workers to check for duplicates (instead of using a constant-time hash lookup), and makes workers harder to compose.

Instead, `Worker` should have a key property that will be compared with keys from other workers to dedup. These keys must be equatable and hashable, i.e. implement `equals` and `hashcode` in Kotlin, and conform to `Hashable` in Swift. We can default to the same behavior we have now, using the worker's type as the key. In Kotlin, workers that take parameters can use themselves as the key if they are data classes. In Swift, they can do the same if they conform to Hashable.

<details>
<summary>Kotlin Implementation Notes</summary>

To make upgrading existing code easier in Kotlin, we might want to introduce this as a sub-interface of `Worker` and deprecate the existing worker `Worker`.

```kotlin
@Deprecated
interface Worker<out T> {
  fun doesSameWorkAs(otherWorker: Worker<*>): Boolean =
    this::class == otherWorker::class
  fun run(): Flow<T>
}

interface KeyedWorker<out T> : Worker<T> {
  
  val key: Any get() = this::class

  override fun doesSameWorkAs(otherWorker: Worker<*>) =
    otherWorker is KeyedWorker && key == otherWorker.key
}
```
</details>

cc @bencochran 

## Tasks
- [ ] Swift implementation
- [ ] Kotlin implementation

**Comment by JustinDSN** [comment]
I think this is another opportunity to use the Swift `5.1` `Identifiable` protocol. Which separates `Identity` of an entity from `state` (`Equality`).

**Comment by dhavalshreyas** [comment]
On the swift side, conforming to `Equatable` / `isEquivalent` has very clear expectations - which lines up with what we need from the `WorkflowNode` perspective. (are these the same workers?).

If we switch to `Key`, the onus will be on the API customers to make sure the key is computed correctly (basically `Type`+`items which impact request`). The two concerns I have with this change are:

* The expectation for what the `Key` should be might not be clear.
* When things go wrong due to incorrect `Key` (maybe we have a `UserFetcherWorker` whose key is also `UserFetcherWorker` instead of `UserFetcherWorker-<UserID>` and we're trying to fetch multiple users), debugging this will not be straightforward.

**Comment by zach-klippenstein** [comment]
> The expectation for what the Key should be might not be clear.

Is documenting this not enough?

> When things go wrong due to incorrect Key (maybe we have a UserFetcherWorker whose key is also UserFetcherWorker instead of UserFetcherWorker-<UserID> and we're trying to fetch multiple users), debugging this will not be straightforward.

How is this any less straightforward (or easier to mess up) than the current API?

**Comment by zach-klippenstein** [comment]
@bencochran Has a Swift proposal for this up in #960.

**Comment by dhavalshreyas** [comment]
> @bencochran Has a Swift proposal for this up in #960.

#960 is for `Screen`

**Comment by dhavalshreyas** [comment]
I believe the intent will be clearer if we have `Worker` conform to `Hashable` and `Equivalent (isEquivalent)` instead of introducing a `Key`. @bencochran would love to hear your thoughts.

**Comment by rjrjr** [comment]
WRT using Identifiable instead: I've always preferred string key approaches to direct implementations of equals and hash (jvm equivalent of identifiable) because it's boilerplate, and so easy to get the contract wrong. It's common to give a base class final equals / hash methods that are based on that key; and to have the key default to the class name. I don't think this is a language-specific concern.

**Comment by rjrjr** [comment]
Note that this is a reversal of Kotlin's move away from keys on workers, because of confusion between them and the key param for `runningWorker`. Should we take a step back and think more holistically about equivalency in general, across Workflow, Worker, and the `run*` methods?

e.g., strawman: 

 * `Worker` and `Workflow` have a base class that defines 
    * a comparison `key: String` properties
    * final `hash` / `equals` methods as suggested above
    * and `withKey(newKey:String): SelfType` type methods that replace the `key` param on `runningWorker`, etc.

That last requirement can't be met exactly on Kotlin, but we could honor such a convention in `StatefulWorkflow`, etc. Or we could keep the `key` param and just document that it overrides the key defined by the worker / workflow.

**Comment by zach-klippenstein** [comment]
> it's boilerplate, and so easy to get the contract wrong.

I don't think either of these things is true in Swift. For most cases, just declare you conform to `Hashable`/`Equatable` and the compiler will automatically generate the necessary implementations.

I would argue it's also not very problematic in kotlin, since most devs are getting the instinct to just make things data classes.

**Comment by dhavalshreyas** [comment]
There're way too many concepts flying around, we should have a glossary to make sure we're talking about the same things 😛 

Definitions from my best understanding (Swift perspective): 

- **Identifiable** - Identifies an item (regardless of content).
- **Equatable** - Exactly the same item and content.
- **Equivalent** - Fields we care about for our purpose are the same.
- **Hashable** - Able to generate an integer that's the same for the same content.

When we require an object to conform to any of these, the intentions are very clear regarding what's required (and as @zach-klippenstein  mentioned, can usually be auto-synthesized in Swift). 

In #960, @bencochran is trying to make `Screen` - `Identifiable` (Even if we don't end up using that particular protocol).

Here, it looks like we'd like for `Worker` to be `Hashable` (along with `Equivalent`, which it already is).

My hope is that we can accomplish this without introducing `Key`. The concern I have with `Key` is that it's not very clear what requirements `Key` needs to fulfill. Based on this PR, we would need `Key` to satisfy `Hashable` and `Equivalent` requirements on the contents of the `Worker` object. However, other reasonable engineers (before reading the docs) could interpret `Key` to mean it needs to `Identify` the object.

**Comment by JustinDSN** [comment]
> Note that this is a reversal of Kotlin's move away from keys on workers, because of confusion between them and the key param for `runningWorker`. Should we take a step back and think more holistically about equivalency in general, across Workflow, Worker, and the `run*` methods?
> 
> e.g., strawman: `Worker` and `Workflow` have a base class that defines
> 
> * a comparison `key: String` properties
> * final `hash` / `equals` methods as suggested above
> * and `withKey(newKey:String): SelfType` type methods that replace the `key` param on `runningWorker`, etc.
> 
> That last requirement can't be met exactly on Kotlin, but we could honor such a convention in `StatefulWorkflow`, etc. Or we could keep the `key` param and just document that it overrides the key defined by the worker / workflow.

I just tried to re-open my previous PR and was immediately tripped up by this reversal. We should definitely come to a concrete decision as to what what we'd like to API too look like and implement this *hopefully* once.

**Comment by dhavalshreyas** [comment]
Would this be resolved by #1021?

**Comment by rjrjr** [comment]
I think so.

**Comment by zach-klippenstein** [comment]
I'm pretty sure #1021 does _not_ solve this, but actually _requires_ this. Even if workers are implemented as workflows, since workflow "identity" is based on the type of the workflow, there's no way to tell the runtime that two different "worker workflows" that have completely separate Worker implementations are different.

Note that there is a subtle variation to this problem that _can_ be solved without this: given the same Worker over two separate render passes, if `doesSameWorkAs` returns false, we can cancel the old worker and start a new one (e.g. storing a unique random value in the worker-workflow's state and changing it in `onPropsChanged` if the workers are different). However, this still doesn't handle the case where two separate workers are ran in the _same render pass_.

We [discussed this on Slack](https://workflow-community.slack.com/archives/GT9FD1XKL/p1592510186112600) as well.

**Comment by zach-klippenstein** [comment]
@dhavalshreyas and I just chatted offline and figured out where we're talking past each other.

## Background

When a workflow runs a worker, the runtime needs to know if the worker was also ran on the last render pass. For this reason, workers have some concept of "identity". Identity is used across two dimensions:

1. Between render passes: Workers across two consecutive render passes that have the same identity will only be started once. This behavior is currently mostly the same between Kotlin and Swift.
2. In the same render pass: The same worker, or different instances of that worker with the same identity, may be "ran" multiple times by the same workflow in the same render pass. This behavior currently differs between Kotlin and Swift.

Let's use a concrete example to reduce ambiguity. Given this setup, using the current `main` version of the runtime:

```kotlin
class MultiWorker(val tag: String) : Worker<Int> {
  override fun doesSameWorkAs(otherWorker): Boolean =
    tag == otherWorker.tag
}

class MyWorkflow {
  override fun render(…) {
    context.runningWorker(MultiWorker("one")) { … }
    context.runningWorker(MultiWorker("two")) { … }
  }
}
```

What is the current behavior of the runtime in Swift vs Kotlin when this is ran, and what happens if a state change causes the first `runningWorker` call to disappear?

- Swift: Two workers will be started. The "one" worker will be cancelled.
- Kotlin: Two workers will be started. The "one" worker will be cancelled.

If we change the workflow implementation to this, so both workers are now fully equivalent:
```kotlin
    context.runningWorker(MultiWorker("one")) { … }
    context.runningWorker(MultiWorker("one")) { … }
```

What happens?

- Swift: Two workers will be started. The second one will be cancelled.
- Kotlin: The context will throw an exception with a message about trying to run two identical workers.

Interestingly, neither Dhaval nor Zach could come up with an actual use case for running the same worker multiple times in the same render pass. The only time you'd probably hit this case is if you implemented `doesSameWorkAs` wrong. Dhaval and Zach disagreed on the pros/cons of the varying behaviors in this "accidental" case – Dhaval said it was good because it's more forgiving, Zach said being forgiving is bad because we should tell you eagerly if you did something you didn't mean to.

## The Problems with GUWT

The refactor that we've been calling "GUWT" changes Workers to no longer be a primary concept that the runtime is aware of, but instead use a lower-level concept called "side effects", and instead implements Workers in terms of a special Workflow. This means the runtime itself is no longer aware of workers' notions of equivalence (`isEquivalent`/`doesSameWorkAs`) – it only sees them as Workflows so can only distinguish them as it would workflows. The special `WorkerWorkflow` is a stateful workflow that maintains some unique arbitrary value to effectively store the result of worker-specific equivalence checks. It changes this value when the equivalence is false, and uses this value as a key to restart the side effect when necessary. This replicates the first "dimension" that equivalence is used in above ("between render passes"), and is the same in both swift and kotlin. The second dimension is where things get messy.

- Swift: Workers of different types can be rendered in the same render pass. Multiple identical workers are no longer allowed to be rendered in the same render pass, doing so results in an error.
- Kotlin: Multiple _workers_, of _any type_, are not allowed to be rendered in the same render pass. This is because while Swift considers the type parameters of a Workflow as part of its type, Kotlin does not, therefore all instances of `WorkerWorkflow` look identical to it.

To solve this issue in Kotlin, we introduced `ImpostorWorkflow`, which effectively lets us reify the type of a workflow that another workflow is wrapping, and consider both part of the identity of the workflow.  

However, both languages still have the problem where two workflows _of the same type_ in the same render pass are always considered equivalent, because the runtime does not have any way to determine that two workflows of the same type are different.

However, a workaround exists: the workflow rendering the workers can pass string keys into the `runningWorker` method, and as long as those keys are distinct, the runtime will see the workers as distinct. Dhaval and Zach both agree this isn't ideal, since it's less pure and forces all changeable inputs for a Worker to be converted to strings, but Zach points out that internally, most workers are already doing this instead of using `doesSameWorkAs` anyway, because it's simpler, and actually doesn't read too badly.

Dhaval and Zach agreed that while this isn't ideal, it's good enough, and it doesn't pay spending a lot of time trying to figure out a solution for a problem that is mostly only theoretical.

**Comment by zach-klippenstein** [comment]
Since we decided not to build a separate key concept at this time, I am closing this issue.
