### ISSUE TITLE
Reconcile redundant worker behavior between Swift and Kotlin

### ISSUE THREAD

**Issue by rjrjr** [square/workflow#994]
In Swift, if you run a worker three times, or three workers of the same type, it's allowed.

In Kotlin, that's a runtime error, and a key must be used to resolve the ambiguity.

We should pick one. To me, the Kotlin behavior is less magical and less error prone.

Related to #961

**Comment by bencochran** [comment]
I think the Kotlin behavior is good, and will mean consistency when Workers are just Workflows (see [GUWT](#1021))

**Comment by zach-klippenstein** [comment]
How does the current swift behavior reconcile the different output handlers for the same worker on the same render pass?

**Comment by dhavalshreyas** [comment]
This should be resolved with #1021, correct?

**Comment by rjrjr** [comment]
Maybe? I think this is worth tracking separately to make sure our
implementations are consistent.

**Comment by zach-klippenstein** [comment]
This is being resolved by GUWT, see https://github.com/square/workflow/issues/961#issuecomment-649776503
