### ISSUE TITLE
Allow renderings to implement ViewBinding, to allow infrastructure containers to not require explicitly registering their bindings

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow#995]
E.g. Instead of having `BackstackRendering` and `BackstackBinding`, you could just have `BackstackRendering` which implements `ViewBinding` _itself_. The rendering machinery would then check the `ViewRegistry` _first_, and if no binding is found, then see if the rendering implements `ViewBinding` before throwing an error. The reason to check the view registry first is so that the registry can override hard-coded rendering bindings.

cc @rjrjr

**Comment by rjrjr** [comment]
Downside is that it means things like BackStackScreen become platform specific. Right now that's a pure kotlin class, in a `common` module.

Needs thinking.

**Comment by zach-klippenstein** [comment]
This isn't a 1.0 blocker, if we want we can add it after, it's not a breaking change.

**Comment by rjrjr** [comment]
Done ages ago. https://github.com/square/workflow-kotlin/blob/main/workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidScreen.kt
